import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import axios from "axios";
import {
  BookOpen, TrendingUp, TrendingDown, DollarSign,
  CheckCircle2, AlertTriangle, Filter, X,
} from "lucide-react";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { format } from "date-fns";
import { SortableTh, useSortState, useSorted } from "@/components/ui/sortable-th";

const BASE = import.meta.env.BASE_URL.replace(/\/$/, "");

// ─── Types ────────────────────────────────────────────────────────────────────
interface JournalEntry {
  id: string;
  entryDate: string;
  paymentHeaderId?: string | null;
  paymentLineId?: string | null;
  debitCoa: string;
  debitCoaName?: string;
  creditCoa: string;
  creditCoaName?: string;
  amount: string;
  entryType?: string | null;
  contractId?: string | null;
  invoiceId?: string | null;
  studentAccountId?: string | null;
  staffId?: string | null;
  autoGenerated: boolean;
  description?: string | null;
  createdOn: string;
}

interface PnlSummary {
  revenue: number;
  cogs: number;
  expense: number;
  grossProfit: number;
  netProfit: number;
  period: { from: string | null; to: string | null };
}

interface BalanceCheck {
  isBalanced: boolean;
  totalEntries: number;
  totalAmount: number;
  nullEntries: number;
  message: string;
}

// ─── Constants ────────────────────────────────────────────────────────────────
const ENTRY_TYPES = [
  { key: "trust_receipt",       label: "Trust Receipt"       },
  { key: "service_fee",         label: "Service Fee"         },
  { key: "school_transfer",     label: "School Transfer"     },
  { key: "commission_received", label: "Commission Received" },
  { key: "cost_payment",        label: "Cost Payment"        },
  { key: "settlement",          label: "Settlement"          },
];

const ENTRY_TYPE_STYLE: Record<string, { bg: string; text: string }> = {
  trust_receipt:       { bg: "#FEF0E3", text: "#C2570A" },
  service_fee:         { bg: "#DCFCE7", text: "#16A34A" },
  school_transfer:     { bg: "#FEF9C3", text: "#CA8A04" },
  commission_received: { bg: "#EDE9FE", text: "#7C3AED" },
  cost_payment:        { bg: "#FEF2F2", text: "#DC2626" },
  settlement:          { bg: "#F0F9FF", text: "#0369A1" },
};

// ─── Empty reference — stable outside component to prevent infinite loops ─────
const EMPTY_JE: JournalEntry[] = [];

// ─── Helpers ──────────────────────────────────────────────────────────────────
function fmtAmt(v: number | string | null | undefined, showSign = false): string {
  if (v === null || v === undefined) return "—";
  const n = Number(v);
  const s = `A$${Math.abs(n).toLocaleString("en-AU", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  if (showSign && n < 0) return `−${s}`;
  return s;
}

function fmtDate(d: string | null | undefined): string {
  if (!d) return "—";
  try { return format(new Date(d), "d MMM yyyy"); } catch { return d; }
}

function entryTypeLabel(key: string | null | undefined): string {
  if (!key) return "—";
  return ENTRY_TYPES.find(t => t.key === key)?.label ?? key;
}

// ─── KPI Card ─────────────────────────────────────────────────────────────────
function KpiCard({
  label, amount, sub, icon: Icon, positive,
}: {
  label: string;
  amount: number;
  sub?: string;
  icon: React.ElementType;
  positive?: boolean;
}) {
  const color = positive === undefined
    ? "#1C1917"
    : amount >= 0
      ? positive ? "#16A34A" : "#DC2626"
      : positive ? "#DC2626" : "#16A34A";

  return (
    <div className="bg-white border border-stone-200 rounded-xl p-4 space-y-1.5">
      <div className="flex items-center justify-between">
        <span className="text-xs font-medium text-stone-500 uppercase tracking-wide">{label}</span>
        <div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{ background: "#FEF0E3" }}>
          <Icon size={14} style={{ color: "#F5821F" }} />
        </div>
      </div>
      <p className="text-xl font-bold" style={{ color }}>
        {fmtAmt(amount)}
      </p>
      {sub && <p className="text-xs text-stone-400">{sub}</p>}
    </div>
  );
}

// ─── DR/CR Cell ───────────────────────────────────────────────────────────────
function CoaCell({ code, name, side }: { code: string; name?: string; side: "DR" | "CR" }) {
  return (
    <span className="inline-flex items-center gap-1">
      <span
        className="text-[10px] font-bold px-1 py-0.5 rounded"
        style={side === "DR"
          ? { background: "#FEF0E3", color: "#C2570A" }
          : { background: "#DCFCE7", color: "#16A34A" }}
      >
        {side}
      </span>
      <span className="font-mono text-xs text-stone-700">{code}</span>
      {name && <span className="text-xs text-stone-400">{name}</span>}
    </span>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────
export default function JournalEntriesPage() {
  const [fromDate,   setFromDate]   = useState("");
  const { sortBy, sortDir, onSort } = useSortState();
  const [toDate,     setToDate]     = useState("");
  const [entryType,  setEntryType]  = useState("");
  const [showFilter, setShowFilter] = useState(false);

  // Build query params
  const params = new URLSearchParams();
  if (fromDate)   params.set("from_date", fromDate);
  if (toDate)     params.set("to_date", toDate);
  if (entryType)  params.set("entry_type", entryType);
  const qs = params.toString();

  // ── P&L Summary ────────────────────────────────────────────────────────────
  const { data: summaryData } = useQuery<PnlSummary>({
    queryKey: ["je-summary", fromDate, toDate],
    queryFn: () => {
      const p = new URLSearchParams();
      if (fromDate) p.set("from_date", fromDate);
      if (toDate)   p.set("to_date", toDate);
      return axios.get(`${BASE}/api/journal-entries/summary?${p}`).then(r => r.data);
    },
  });

  // ── Balance Check ───────────────────────────────────────────────────────────
  const { data: balanceData } = useQuery<BalanceCheck>({
    queryKey: ["je-balance"],
    queryFn: () => axios.get(`${BASE}/api/journal-entries/balance-check`).then(r => r.data),
    staleTime: 60_000,
  });

  // ── Journal Entries List ────────────────────────────────────────────────────
  const { data: jeData, isLoading } = useQuery({
    queryKey: ["journal-entries-page", qs],
    queryFn: () =>
      axios.get(`${BASE}/api/journal-entries?${qs}`).then(r => r.data),
  });

  const entries: JournalEntry[] = jeData?.data ?? EMPTY_JE;
  const sorted = useSorted(entries, sortBy, sortDir);
  const summary = summaryData;
  const balance = balanceData;

  const hasFilters = !!(fromDate || toDate || entryType);

  function clearFilters() {
    setFromDate("");
    setToDate("");
    setEntryType("");
  }

  return (
    <div className="p-6 space-y-6">

      {/* ── Page Header ────────────────────────────────────────────────────── */}
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-3xl font-bold text-stone-800">Journal Entries</h1>
          <p className="text-sm text-stone-500 mt-1">
            Double-entry ledger — auto-generated from every payment transaction
          </p>
        </div>
        {/* Balance Check badge */}
        {balance && (
          <div
            className="flex items-center gap-2 px-3 py-2 rounded-xl border text-sm font-medium"
            style={balance.isBalanced
              ? { background: "#DCFCE7", borderColor: "#BBF7D0", color: "#16A34A" }
              : { background: "#FEF2F2", borderColor: "#FECACA", color: "#DC2626" }}
          >
            {balance.isBalanced
              ? <CheckCircle2 size={15} />
              : <AlertTriangle size={15} />}
            {balance.isBalanced
              ? `Balanced · ${balance.totalEntries.toLocaleString()} entries`
              : `${balance.nullEntries} unbalanced entries`}
          </div>
        )}
      </div>

      {/* ── P&L KPI Cards ──────────────────────────────────────────────────── */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-4">
        <KpiCard
          label="Revenue"
          amount={summary?.revenue ?? 0}
          sub="Credit 3xx accounts"
          icon={TrendingUp}
          positive={true}
        />
        <KpiCard
          label="COGS"
          amount={summary?.cogs ?? 0}
          sub="Debit 4xx accounts"
          icon={TrendingDown}
          positive={false}
        />
        <KpiCard
          label="Expenses"
          amount={summary?.expense ?? 0}
          sub="Debit 5xx accounts"
          icon={DollarSign}
          positive={false}
        />
        <KpiCard
          label="Gross Profit"
          amount={summary?.grossProfit ?? 0}
          sub="Revenue − COGS"
          icon={TrendingUp}
          positive={true}
        />
        <KpiCard
          label="Net Profit"
          amount={summary?.netProfit ?? 0}
          sub="Gross − Expenses"
          icon={BookOpen}
          positive={true}
        />
      </div>

      {/* ── Filter Bar ─────────────────────────────────────────────────────── */}
      <div className="flex flex-wrap items-center gap-3">
        {/* Entry type pills */}
        <div className="flex flex-wrap gap-1.5">
          <button
            onClick={() => setEntryType("")}
            className={`px-3 py-1 rounded-full text-xs font-medium border transition-all ${
              entryType === ""
                ? "border-[#F5821F] bg-[#FEF0E3] text-[#F5821F]"
                : "border-stone-200 text-stone-500 hover:border-stone-300"
            }`}
          >
            All Types
          </button>
          {ENTRY_TYPES.map(t => (
            <button
              key={t.key}
              onClick={() => setEntryType(e => e === t.key ? "" : t.key)}
              className={`px-3 py-1 rounded-full text-xs font-medium border transition-all ${
                entryType === t.key
                  ? "border-[#F5821F] bg-[#FEF0E3] text-[#F5821F]"
                  : "border-stone-200 text-stone-500 hover:border-stone-300"
              }`}
            >
              {t.label}
            </button>
          ))}
        </div>

        {/* Date range */}
        <div className="flex items-center gap-2 ml-auto">
          <Input
            type="date"
            value={fromDate}
            onChange={e => setFromDate(e.target.value)}
            className="h-9 text-sm w-36"
          />
          <span className="text-stone-400 text-sm">—</span>
          <Input
            type="date"
            value={toDate}
            onChange={e => setToDate(e.target.value)}
            className="h-9 text-sm w-36"
          />
          {hasFilters && (
            <button
              onClick={clearFilters}
              className="flex items-center gap-1 px-2.5 py-1.5 rounded-lg border border-stone-200 text-xs text-stone-500 hover:bg-stone-50"
            >
              <X size={12} /> Clear
            </button>
          )}
        </div>
      </div>

      {/* Active filter tags */}
      {hasFilters && (
        <div className="flex flex-wrap gap-2">
          {entryType && (
            <span className="flex items-center gap-1.5 px-2.5 py-1 rounded-full border text-xs font-medium"
              style={{ background: "#FEF0E3", borderColor: "#FDBA74", color: "#C2570A" }}>
              <Filter size={10} />
              {entryTypeLabel(entryType)}
              <button onClick={() => setEntryType("")} className="ml-0.5 hover:text-[#F5821F]"><X size={10} /></button>
            </span>
          )}
          {fromDate && (
            <span className="flex items-center gap-1.5 px-2.5 py-1 rounded-full border text-xs font-medium"
              style={{ background: "#FEF0E3", borderColor: "#FDBA74", color: "#C2570A" }}>
              From {fmtDate(fromDate)}
              <button onClick={() => setFromDate("")} className="ml-0.5 hover:text-[#F5821F]"><X size={10} /></button>
            </span>
          )}
          {toDate && (
            <span className="flex items-center gap-1.5 px-2.5 py-1 rounded-full border text-xs font-medium"
              style={{ background: "#FEF0E3", borderColor: "#FDBA74", color: "#C2570A" }}>
              To {fmtDate(toDate)}
              <button onClick={() => setToDate("")} className="ml-0.5 hover:text-[#F5821F]"><X size={10} /></button>
            </span>
          )}
        </div>
      )}

      {/* ── Table ──────────────────────────────────────────────────────────── */}
      <div className="rounded-xl border border-stone-200 overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="bg-stone-50 border-b border-stone-200">
              <SortableTh col="entryDate" sortBy={sortBy} sortDir={sortDir} onSort={onSort} className="text-left px-4 py-3 text-xs font-semibold text-stone-500 uppercase tracking-wide w-32">Date</SortableTh>
              <SortableTh col="entryType" sortBy={sortBy} sortDir={sortDir} onSort={onSort} className="text-left px-4 py-3 text-xs font-semibold text-stone-500 uppercase tracking-wide">Entry Type</SortableTh>
              <SortableTh col="debitAccountName" sortBy={sortBy} sortDir={sortDir} onSort={onSort} className="text-left px-4 py-3 text-xs font-semibold text-stone-500 uppercase tracking-wide">Debit Account</SortableTh>
              <SortableTh col="creditAccountName" sortBy={sortBy} sortDir={sortDir} onSort={onSort} className="text-left px-4 py-3 text-xs font-semibold text-stone-500 uppercase tracking-wide">Credit Account</SortableTh>
              <SortableTh col="amount" sortBy={sortBy} sortDir={sortDir} onSort={onSort} className="text-right px-4 py-3 text-xs font-semibold text-stone-500 uppercase tracking-wide w-32">Amount (AUD)</SortableTh>
              <SortableTh col="description" sortBy={sortBy} sortDir={sortDir} onSort={onSort} className="text-left px-4 py-3 text-xs font-semibold text-stone-500 uppercase tracking-wide">Description</SortableTh>
              <th className="text-center px-4 py-3 text-xs font-semibold text-stone-500 uppercase tracking-wide w-20">Source</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-stone-100">
            {isLoading ? (
              <tr>
                <td colSpan={7} className="text-center py-16 text-stone-400 text-sm">
                  Loading journal entries…
                </td>
              </tr>
            ) : entries.length === 0 ? (
              <tr>
                <td colSpan={7} className="text-center py-16">
                  <div className="flex flex-col items-center gap-3 text-stone-400">
                    <BookOpen size={32} strokeWidth={1.2} />
                    <p className="text-sm font-medium">No journal entries found</p>
                    {hasFilters && (
                      <button onClick={clearFilters}
                        className="text-xs text-[#F5821F] hover:underline">
                        Clear filters
                      </button>
                    )}
                  </div>
                </td>
              </tr>
            ) : (
              sorted.map(je => {
                const typeStyle = ENTRY_TYPE_STYLE[je.entryType ?? ""] ?? { bg: "#F4F3F1", text: "#57534E" };
                return (
                  <tr key={je.id} className="hover:bg-[#FEF0E3] cursor-pointer transition-colors">
                    {/* Date */}
                    <td className="px-4 py-3 text-stone-700 tabular-nums text-xs whitespace-nowrap">
                      {fmtDate(je.entryDate)}
                    </td>

                    {/* Entry Type */}
                    <td className="px-4 py-3">
                      {je.entryType ? (
                        <span
                          className="inline-block px-2 py-0.5 rounded-full text-xs font-semibold whitespace-nowrap"
                          style={{ background: typeStyle.bg, color: typeStyle.text }}
                        >
                          {entryTypeLabel(je.entryType)}
                        </span>
                      ) : <span className="text-stone-300">—</span>}
                    </td>

                    {/* Debit */}
                    <td className="px-4 py-3">
                      <CoaCell code={je.debitCoa} name={je.debitCoaName} side="DR" />
                    </td>

                    {/* Credit */}
                    <td className="px-4 py-3">
                      <CoaCell code={je.creditCoa} name={je.creditCoaName} side="CR" />
                    </td>

                    {/* Amount */}
                    <td className="px-4 py-3 text-right font-semibold text-stone-800 tabular-nums whitespace-nowrap">
                      {fmtAmt(je.amount)}
                    </td>

                    {/* Description */}
                    <td className="px-4 py-3 text-xs text-stone-500 max-w-[220px] truncate">
                      {je.description ?? "—"}
                    </td>

                    {/* Source: auto vs manual */}
                    <td className="px-4 py-3 text-center">
                      {je.autoGenerated ? (
                        <span className="inline-flex items-center gap-1 text-xs text-emerald-600">
                          <CheckCircle2 size={12} /> Auto
                        </span>
                      ) : (
                        <span className="text-xs text-stone-400">Manual</span>
                      )}
                    </td>
                  </tr>
                );
              })
            )}
          </tbody>
        </table>

        {/* Footer totals */}
        {entries.length > 0 && (
          <div className="px-4 py-3 bg-stone-50 border-t border-stone-200 flex items-center justify-between">
            <span className="text-xs text-stone-500">
              {entries.length.toLocaleString()} {entries.length === 1 ? "entry" : "entries"}
              {entries.length >= 500 && " (showing latest 500)"}
            </span>
            <span className="text-sm font-bold text-stone-800">
              Total: {fmtAmt(entries.reduce((s, e) => s + Number(e.amount ?? 0), 0))}
            </span>
          </div>
        )}
      </div>

      {/* ── Double-entry note ──────────────────────────────────────────────── */}
      <div className="flex items-start gap-2.5 bg-stone-50 border border-stone-200 rounded-xl p-4">
        <BookOpen size={15} className="text-stone-400 mt-0.5 shrink-0" />
        <p className="text-xs text-stone-500 leading-relaxed">
          Each row represents one double-entry journal entry with a matching DR and CR.
          Entries are auto-generated when a payment line is recorded.
          <strong className="text-stone-600"> P&L Summary</strong> above reflects the filtered period
          and uses CoA account type prefixes: Revenue (3xx), COGS (4xx), Expenses (5xx).
        </p>
      </div>
    </div>
  );
}
