import { useState, useMemo, useRef, useEffect } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useLocation } from "wouter";
import axios from "axios";
import {
  Plus, X, Trash2, ChevronsRight, BookOpen,
  CheckCircle2, AlertTriangle, ChevronDown, ExternalLink,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { format } from "date-fns";
import { SortableTh, useSortState, useSorted } from "@/components/ui/sortable-th";

const BASE = import.meta.env.BASE_URL.replace(/\/$/, "");

// ─── Types ───────────────────────────────────────────────────────────────────
interface PaymentHeader {
  id: string;
  paymentRef?: string | null;
  paymentDate: string;
  paymentType: string;
  paymentMethod?: string | null;
  totalAmount?: string | null;
  bankReference?: string | null;
  notes?: string | null;
  status: string;
  createdOn: string;
  receivedFrom?: string | null;
  paidTo?: string | null;
}

interface JournalEntry {
  id: string;
  entryDate: string;
  paymentHeaderId?: string | null;
  paymentRef?: string | null;
  paymentStatus?: string | null;
  debitCoa: string;
  debitCoaName?: string;
  creditCoa: string;
  creditCoaName?: string;
  amount: string;
  entryType?: string | null;
  contractId?: string | null;
  autoGenerated: boolean;
  createdOn: string;
}

interface SplitLine {
  uid: string;
  contractProductId: string;
  contractId: string;
  contractNumber: string;
  productName: string;
  coaCode: string;
  splitType: string;
  amount: string;
  description: string;
}

interface AccountOption {
  id: string;
  name: string;
  accountType: string;
}

// ─── Constants ───────────────────────────────────────────────────────────────
const PAYMENT_TYPES: Array<{ key: string; label: string }> = [
  { key: "trust_receipt",  label: "Trust Receipt"  },
  { key: "trust_transfer", label: "Trust Transfer" },
  { key: "commission",     label: "Commission"     },
  { key: "direct",         label: "Direct"         },
];

const PAYMENT_METHODS = ["Bank Transfer", "Cash", "Card", "Cheque", "EFT"];

const JE_PREVIEW: Record<string, { debit: string; credit: string; debitLabel: string; creditLabel: string }> = {
  trust_receipt:  { debit: "1200", credit: "1300", debitLabel: "Trust Account",                creditLabel: "AR — Commission Receivable"   },
  trust_transfer: { debit: "2100", credit: "1200", debitLabel: "AP — Student Tuition Payable", creditLabel: "Trust Account"                },
  commission:     { debit: "1100", credit: "3100", debitLabel: "Cash & Bank — Operating",      creditLabel: "Commission — Tuition"         },
  direct:         { debit: "4700", credit: "1100", debitLabel: "Direct — Other",               creditLabel: "Cash & Bank — Operating"      },
};

const STATUS_STYLE: Record<string, { bg: string; text: string }> = {
  Active: { bg: "#DCFCE7", text: "#16A34A" },
  Void:   { bg: "#FEF2F2", text: "#DC2626" },
};

const TYPE_STYLE: Record<string, string> = {
  trust_receipt:  "#FEF0E3",
  trust_transfer: "#FEF9C3",
  commission:     "#DCFCE7",
  direct:         "#F4F3F1",
};

// ─── Helpers ─────────────────────────────────────────────────────────────────
function fmtAmt(v: string | null | undefined): string {
  if (!v) return "—";
  return `A$${Number(v).toLocaleString("en-AU", { minimumFractionDigits: 2 })}`;
}
function fmtDate(d: string | null | undefined): string {
  if (!d) return "—";
  try { return format(new Date(d), "MMM d, yyyy"); } catch { return d; }
}
function parseNotes(notes: string | null | undefined): { receivedFromName?: string; paidToName?: string; notes?: string } {
  if (!notes) return {};
  try { return JSON.parse(notes); } catch { return { notes: notes ?? undefined }; }
}
function newLine(): SplitLine {
  return { uid: crypto.randomUUID(), contractProductId: "", contractId: "", contractNumber: "", productName: "", coaCode: "", splitType: "principal", amount: "", description: "" };
}

// ─── Account Combobox ─────────────────────────────────────────────────────────
function AccountCombobox({
  value, onChange, placeholder,
}: {
  value: AccountOption | null;
  onChange: (v: AccountOption | null) => void;
  placeholder: string;
}) {
  const [search, setSearch] = useState("");
  const [open, setOpen]     = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  const { data: results = [] } = useQuery<AccountOption[]>({
    queryKey: ["pay-acct-lookup", search],
    queryFn: () =>
      axios.get(`${BASE}/api/accounting/payments-lookup/accounts?search=${encodeURIComponent(search)}`).then(r => r.data),
    enabled: search.length >= 1,
  });

  useEffect(() => {
    function handler(e: MouseEvent) {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    }
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, []);

  if (value) {
    return (
      <div className="flex items-center gap-2 h-9 px-3 border border-stone-200 rounded-md bg-stone-50 text-sm">
        <span className="flex-1 font-medium text-stone-800 truncate">{value.name}</span>
        <span className="text-xs text-stone-400 shrink-0">{value.accountType}</span>
        <button onClick={() => onChange(null)} className="text-stone-300 hover:text-red-500 transition-colors shrink-0">
          <X size={12} />
        </button>
      </div>
    );
  }

  return (
    <div ref={ref} className="relative">
      <Input
        value={search}
        onChange={e => { setSearch(e.target.value); setOpen(true); }}
        onFocus={() => setOpen(true)}
        placeholder={placeholder}
        className="h-9 text-sm"
      />
      {open && results.length > 0 && (
        <div className="absolute top-10 left-0 right-0 z-50 bg-white border border-stone-200 rounded-xl shadow-lg max-h-48 overflow-y-auto">
          {results.map(a => (
            <button
              key={a.id}
              onMouseDown={() => { onChange(a); setSearch(""); setOpen(false); }}
              className="w-full text-left px-3 py-2 text-sm hover:bg-orange-50 flex items-center gap-2"
            >
              <span className="font-medium text-stone-800 flex-1 truncate">{a.name}</span>
              <span className="text-xs text-stone-400 shrink-0">{a.accountType}</span>
            </button>
          ))}
        </div>
      )}
      {open && search.length >= 1 && results.length === 0 && (
        <div className="absolute top-10 left-0 right-0 z-50 bg-white border border-stone-200 rounded-xl shadow-sm px-3 py-2 text-xs text-stone-400">
          No accounts found
        </div>
      )}
    </div>
  );
}

// ─── Contract Product Picker (per split line) ─────────────────────────────────
function ContractProductPicker({
  line, paymentType, onUpdate, onContractSelect,
}: {
  line: SplitLine;
  paymentType: string;
  onUpdate: (uid: string, fields: Partial<SplitLine>) => void;
  onContractSelect: (accountId: string, accountName: string) => void;
}) {
  const [search, setSearch] = useState("");
  const [open, setOpen]     = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  const { data: contracts = [] } = useQuery<any[]>({
    queryKey: ["pay-contract-lookup", search],
    queryFn: () =>
      axios.get(`${BASE}/api/accounting/payments-lookup/contracts?search=${encodeURIComponent(search)}`).then(r => r.data),
    enabled: search.length >= 1,
  });

  const { data: products = [] } = useQuery<any[]>({
    queryKey: ["pay-products-lookup", line.contractId],
    queryFn: () =>
      axios.get(`${BASE}/api/accounting/payments-lookup/contracts/${line.contractId}/products`).then(r => r.data),
    enabled: !!line.contractId,
  });

  useEffect(() => {
    function handler(e: MouseEvent) {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    }
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, []);

  function clearContract() {
    onUpdate(line.uid, { contractId: "", contractNumber: "", contractProductId: "", productName: "", amount: "" });
  }

  if (line.contractId) {
    return (
      <div className="space-y-1">
        <div className="flex items-center gap-1">
          <span className="bg-orange-50 border border-orange-200 text-orange-700 text-xs font-mono px-2 py-0.5 rounded">
            {line.contractNumber}
          </span>
          <button onClick={clearContract} className="text-stone-300 hover:text-red-500 transition-colors">
            <X size={10} />
          </button>
        </div>
        <Select
          value={line.contractProductId}
          onValueChange={v => {
            const p = products.find((p: any) => p.id === v);
            if (!p) return;
            const amt = paymentType === "trust_transfer"
              ? (p.ap_amount ?? "0")
              : (p.ar_amount ?? "0");
            onUpdate(line.uid, {
              contractProductId: v,
              productName: p.name ?? "",
              amount: String(Number(amt).toFixed(2)),
            });
          }}
        >
          <SelectTrigger className="h-7 text-xs border-stone-200">
            <SelectValue placeholder="Select product…" />
          </SelectTrigger>
          <SelectContent>
            {products.map((p: any) => {
              const amt = paymentType === "trust_transfer" ? p.ap_amount : p.ar_amount;
              const status = paymentType === "trust_transfer" ? p.ap_status : p.ar_status;
              return (
                <SelectItem key={p.id} value={p.id}>
                  <span className="flex items-center gap-2">
                    <span>{p.name}</span>
                    <span className="text-stone-400">A${Number(amt ?? 0).toFixed(2)}</span>
                    {status === "paid" && <span className="text-green-600 text-xs">✓paid</span>}
                  </span>
                </SelectItem>
              );
            })}
          </SelectContent>
        </Select>
      </div>
    );
  }

  return (
    <div ref={ref} className="relative">
      <Input
        value={search}
        onChange={e => { setSearch(e.target.value); setOpen(true); }}
        onFocus={() => setOpen(true)}
        placeholder="Search contract…"
        className="h-7 text-xs"
      />
      {open && contracts.length > 0 && (
        <div className="absolute top-8 left-0 z-50 w-64 bg-white border border-stone-200 rounded-xl shadow-lg max-h-40 overflow-y-auto">
          {contracts.map((c: any) => (
            <button
              key={c.id}
              onMouseDown={() => {
                onUpdate(line.uid, {
                  contractId: c.id,
                  contractNumber: c.contract_number ?? c.id.slice(0, 8),
                });
                if (c.account_id && c.account_name) {
                  onContractSelect(c.account_id, c.account_name);
                }
                setSearch("");
                setOpen(false);
              }}
              className="w-full text-left px-3 py-2 hover:bg-orange-50"
            >
              <div className="text-xs font-medium text-stone-800">
                {c.contract_number} — {c.student_name}
              </div>
              <div className="text-xs text-stone-400">{c.account_name}</div>
            </button>
          ))}
        </div>
      )}
      {open && search.length >= 1 && contracts.length === 0 && (
        <div className="absolute top-8 left-0 right-0 z-50 bg-white border border-stone-200 rounded-xl shadow-sm px-3 py-2 text-xs text-stone-400">
          No contracts found
        </div>
      )}
    </div>
  );
}

// ─── Void Action dropdown ────────────────────────────────────────────────────
function VoidAction({ paymentId, status, isSuperAdmin }: { paymentId: string; status: string; isSuperAdmin: boolean }) {
  const [open, setOpen] = useState(false);
  const { toast } = useToast();
  const qc = useQueryClient();

  const voidMutation = useMutation({
    mutationFn: () => axios.patch(`${BASE}/api/accounting/payments/${paymentId}/void`).then(r => r.data),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["payments"] });
      qc.invalidateQueries({ queryKey: ["journal-entries"] });
      toast({ title: "Payment voided" });
      setOpen(false);
    },
    onError: () => toast({ title: "Void failed", variant: "destructive" }),
  });

  if (!isSuperAdmin || status === "Void") return null;

  return (
    <div className="relative inline-block">
      <button onClick={() => setOpen(o => !o)}
        className="flex items-center gap-1 px-2 py-1 rounded border border-stone-200 text-xs text-stone-600 hover:bg-stone-50">
        <ChevronDown size={11} />
      </button>
      {open && (
        <>
          <div className="fixed inset-0 z-10" onClick={() => setOpen(false)} />
          <div className="absolute right-0 top-7 z-20 w-36 bg-white border border-stone-200 rounded-xl shadow-lg py-1">
            <button
              onClick={() => voidMutation.mutate()}
              disabled={voidMutation.isPending}
              className="w-full text-left px-3 py-2 text-sm text-red-600 hover:bg-red-50"
            >
              {voidMutation.isPending ? "Voiding…" : "Void Payment"}
            </button>
          </div>
        </>
      )}
    </div>
  );
}

// ─── JE Tab Void (by paymentHeaderId) ────────────────────────────────────────
function JeVoidAction({ je, isSuperAdmin }: { je: JournalEntry; isSuperAdmin: boolean }) {
  const [open, setOpen] = useState(false);
  const { toast } = useToast();
  const qc = useQueryClient();

  const voidMutation = useMutation({
    mutationFn: () =>
      axios.patch(`${BASE}/api/accounting/payments/${je.paymentHeaderId}/void`).then(r => r.data),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["payments"] });
      qc.invalidateQueries({ queryKey: ["journal-entries"] });
      toast({ title: "Payment voided" });
      setOpen(false);
    },
    onError: () => toast({ title: "Void failed", variant: "destructive" }),
  });

  if (!isSuperAdmin || !je.paymentHeaderId || je.paymentStatus === "Void") return null;

  return (
    <div className="relative inline-block">
      <button onClick={() => setOpen(o => !o)}
        className="p-1 rounded hover:bg-red-50 text-stone-400 hover:text-red-600 transition-colors">
        <ChevronDown size={13} />
      </button>
      {open && (
        <>
          <div className="fixed inset-0 z-10" onClick={() => setOpen(false)} />
          <div className="absolute right-0 top-7 z-20 w-36 bg-white border border-stone-200 rounded-xl shadow-lg py-1">
            <button
              onClick={() => voidMutation.mutate()}
              disabled={voidMutation.isPending}
              className="w-full text-left px-3 py-2 text-sm text-red-600 hover:bg-red-50"
            >
              {voidMutation.isPending ? "Voiding…" : "Void Payment"}
            </button>
          </div>
        </>
      )}
    </div>
  );
}

// ─── Create Payment Sheet ─────────────────────────────────────────────────────
function CreateSheet({ onClose }: { onClose: () => void }) {
  const { toast } = useToast();
  const qc = useQueryClient();

  const [paymentType,   setPaymentType]   = useState("trust_receipt");
  const [paymentDate,   setPaymentDate]   = useState(new Date().toISOString().slice(0, 10));
  const [paymentMethod, setPaymentMethod] = useState("Bank Transfer");
  const [receivedFrom,  setReceivedFrom]  = useState<AccountOption | null>(null);
  const [paidTo,        setPaidTo]        = useState<AccountOption | null>(null);
  const [bankReference, setBankReference] = useState("");
  const [notes,         setNotes]         = useState("");
  const [lines,         setLines]         = useState<SplitLine[]>([newLine()]);

  const total = lines.reduce((s, l) => s + Number(l.amount || 0), 0);
  const je    = JE_PREVIEW[paymentType];

  function updateLine(uid: string, fields: Partial<SplitLine>) {
    setLines(prev => prev.map(l => l.uid === uid ? { ...l, ...fields } : l));
  }

  function handleContractSelect(accountId: string, accountName: string) {
    if (paymentType === "trust_receipt" && !receivedFrom) {
      setReceivedFrom({ id: accountId, name: accountName, accountType: "Others" });
    } else if (paymentType === "trust_transfer" && !paidTo) {
      setPaidTo({ id: accountId, name: accountName, accountType: "Others" });
    }
  }

  const createMutation = useMutation({
    mutationFn: () => axios.post(`${BASE}/api/accounting/payments`, {
      paymentDate, paymentMethod, paymentType,
      bankReference:    bankReference || null,
      notes:            notes || null,
      receivedFromId:   receivedFrom?.id   || null,
      receivedFromName: receivedFrom?.name || null,
      paidToId:         paidTo?.id         || null,
      paidToName:       paidTo?.name       || null,
      lines: lines.map(l => ({
        contractProductId: l.contractProductId || null,
        coaCode:           l.coaCode || null,
        splitType:         l.splitType || null,
        amount:            Number(l.amount || 0),
        description:       l.description || null,
      })),
    }).then(r => r.data),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["payments"] });
      qc.invalidateQueries({ queryKey: ["journal-entries"] });
      qc.invalidateQueries({ queryKey: ["ar-summary"] });
      qc.invalidateQueries({ queryKey: ["ar"] });
      qc.invalidateQueries({ queryKey: ["ap"] });
      toast({ title: "Payment created + Journal Entry generated" });
      onClose();
    },
    onError: () => toast({ title: "Payment failed", variant: "destructive" }),
  });

  return (
    <div className="fixed inset-0 z-50 flex justify-end bg-black/30 backdrop-blur-sm">
      <div className="w-full max-w-lg bg-white shadow-2xl flex flex-col h-full overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-stone-200 shrink-0">
          <h3 className="text-base font-bold text-stone-800">Create Payment</h3>
          <button onClick={onClose} className="p-1.5 rounded hover:bg-stone-100">
            <X size={16} className="text-stone-400" />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-5 space-y-5">
          {/* Payment Type */}
          <div className="space-y-2">
            <Label className="text-xs font-medium text-stone-600">Payment Type</Label>
            <div className="flex gap-2 flex-wrap">
              {PAYMENT_TYPES.map(t => (
                <button
                  key={t.key}
                  onClick={() => setPaymentType(t.key)}
                  className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition-all ${
                    paymentType === t.key
                      ? "border-[#F5821F] bg-[#FEF0E3] text-[#F5821F]"
                      : "border-stone-200 text-stone-600 hover:border-stone-400"
                  }`}
                >
                  {t.label}
                </button>
              ))}
            </div>
          </div>

          {/* Core Fields */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div className="space-y-1.5">
              <Label className="text-xs font-medium text-stone-600">Payment Date</Label>
              <Input type="date" value={paymentDate} onChange={e => setPaymentDate(e.target.value)}
                className="h-9 text-sm" />
            </div>
            <div className="space-y-1.5">
              <Label className="text-xs font-medium text-stone-600">Payment Method</Label>
              <Select value={paymentMethod} onValueChange={setPaymentMethod}>
                <SelectTrigger className="h-9 text-sm"><SelectValue /></SelectTrigger>
                <SelectContent>
                  {PAYMENT_METHODS.map(m => <SelectItem key={m} value={m}>{m}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1.5">
              <Label className="text-xs font-medium text-stone-600">
                Received From
                <span className="ml-1 text-stone-400 font-normal">(Account)</span>
              </Label>
              <AccountCombobox
                value={receivedFrom}
                onChange={setReceivedFrom}
                placeholder="Search account…"
              />
            </div>
            <div className="space-y-1.5">
              <Label className="text-xs font-medium text-stone-600">
                Paid To
                <span className="ml-1 text-stone-400 font-normal">(Account)</span>
              </Label>
              <AccountCombobox
                value={paidTo}
                onChange={setPaidTo}
                placeholder="Search account…"
              />
            </div>
            <div className="col-span-2 space-y-1.5">
              <Label className="text-xs font-medium text-stone-600">Bank Reference</Label>
              <Input value={bankReference} onChange={e => setBankReference(e.target.value)}
                placeholder="e.g. BSB/Account, transfer ref…" className="h-9 text-sm" />
            </div>
          </div>

          {/* Split Lines */}
          <div className="space-y-2">
            <Label className="text-xs font-medium text-stone-600 uppercase tracking-wide">Split Lines</Label>
            <div className="border border-stone-200 rounded-xl overflow-hidden">
              <table className="w-full text-xs">
                <thead className="bg-stone-50 border-b border-stone-100">
                  <tr>
                    <th className="text-left px-3 py-2 text-stone-400 font-medium">Contract / Product</th>
                    <th className="text-left px-3 py-2 text-stone-400 font-medium w-20">COA</th>
                    <th className="text-left px-3 py-2 text-stone-400 font-medium w-24">Split Type</th>
                    <th className="text-left px-3 py-2 text-stone-400 font-medium w-24">Amount (AUD)</th>
                    <th className="w-7" />
                  </tr>
                </thead>
                <tbody className="divide-y divide-stone-50">
                  {lines.map(line => (
                    <tr key={line.uid}>
                      <td className="px-2 py-1.5 min-w-[160px]">
                        <ContractProductPicker
                          line={line}
                          paymentType={paymentType}
                          onUpdate={updateLine}
                          onContractSelect={handleContractSelect}
                        />
                      </td>
                      <td className="px-2 py-1.5">
                        <Input
                          value={line.coaCode}
                          onChange={e => updateLine(line.uid, { coaCode: e.target.value })}
                          className="h-7 text-xs border-stone-200 font-mono" placeholder="1200" />
                      </td>
                      <td className="px-2 py-1.5">
                        <Select
                          value={line.splitType}
                          onValueChange={v => updateLine(line.uid, { splitType: v })}
                        >
                          <SelectTrigger className="h-7 text-xs border-stone-200">
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            {["principal", "commission", "fee", "tax", "other"].map(s => (
                              <SelectItem key={s} value={s}>{s}</SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </td>
                      <td className="px-2 py-1.5">
                        <Input
                          type="number" min={0} step="0.01"
                          value={line.amount}
                          onChange={e => updateLine(line.uid, { amount: e.target.value })}
                          className="h-7 text-xs border-stone-200" placeholder="0.00" />
                      </td>
                      <td className="px-2 py-1.5">
                        <button onClick={() => setLines(prev => prev.filter(l => l.uid !== line.uid))}
                          className="p-0.5 rounded hover:bg-red-50 text-stone-300 hover:text-red-500">
                          <Trash2 size={12} />
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
              <div className="px-3 py-2 flex items-center justify-between border-t border-stone-100">
                <button onClick={() => setLines(prev => [...prev, newLine()])}
                  className="flex items-center gap-1 text-xs text-[#F5821F] hover:underline font-medium">
                  <Plus size={12} /> Add Line
                </button>
                <span className="text-xs font-bold text-stone-800">
                  Total: A${total.toLocaleString("en-AU", { minimumFractionDigits: 2 })}
                </span>
              </div>
            </div>
          </div>

          {/* JE Preview */}
          {je && (
            <div className="bg-stone-50 border border-stone-200 rounded-xl p-4 space-y-2">
              <div className="flex items-center gap-2 text-xs font-semibold text-stone-600 uppercase tracking-wide">
                <BookOpen size={13} /> Journal Entry Preview
              </div>
              <div className="space-y-1 font-mono text-sm">
                <div className="flex justify-between">
                  <span className="text-stone-500">DR <span className="text-stone-800">{je.debit}</span> {je.debitLabel}</span>
                  <span className="font-semibold text-stone-800">
                    A${total.toLocaleString("en-AU", { minimumFractionDigits: 2 })}
                  </span>
                </div>
                <div className="flex justify-between pl-4">
                  <span className="text-stone-500">CR <span className="text-stone-800">{je.credit}</span> {je.creditLabel}</span>
                  <span className="font-semibold text-stone-800">
                    A${total.toLocaleString("en-AU", { minimumFractionDigits: 2 })}
                  </span>
                </div>
              </div>
            </div>
          )}

          {/* Notes */}
          <div className="space-y-1.5">
            <Label className="text-xs font-medium text-stone-600">Notes</Label>
            <Textarea value={notes} onChange={e => setNotes(e.target.value)}
              className="text-sm min-h-[60px] resize-none" placeholder="Internal notes…" />
          </div>
        </div>

        {/* Footer */}
        <div className="px-5 py-4 border-t border-stone-200 shrink-0">
          <Button
            onClick={() => createMutation.mutate()}
            disabled={createMutation.isPending}
            className="w-full text-white flex items-center justify-center gap-2"
            style={{ background: "#F5821F" }}
          >
            <ChevronsRight size={15} />
            {createMutation.isPending ? "Creating…" : "Save & Create Journal Entry"}
          </Button>
        </div>
      </div>
    </div>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────
export default function PaymentsPage() {
  const [, navigate]          = useLocation();
  const { sortBy, sortDir, onSort } = useSortState();
  const [showCreate, setShowCreate] = useState(false);
  const [typeFilter, setTypeFilter] = useState("");
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo,   setDateTo]   = useState("");

  // Super admin check — wire to auth context in production
  const isSuperAdmin = true;

  const { data: paymentsData, isLoading: paymentsLoading } = useQuery({
    queryKey: ["payments", typeFilter, dateFrom, dateTo],
    queryFn: () => {
      const p = new URLSearchParams();
      if (typeFilter) p.set("paymentType", typeFilter);
      if (dateFrom)   p.set("date_from", dateFrom);
      if (dateTo)     p.set("date_to", dateTo);
      return axios.get(`${BASE}/api/accounting/payments?${p}`).then(r => r.data);
    },
  });

  const payments: PaymentHeader[] = paymentsData?.data ?? [];
  const sortedPayments = useSorted(payments, sortBy, sortDir);

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-3xl font-bold text-stone-800">Payments</h1>
          <p className="text-sm text-stone-500 mt-1">Trust receipts, transfers, commissions and direct payments</p>
        </div>
        <Button
          onClick={() => setShowCreate(true)}
          className="flex items-center gap-2 text-white rounded-lg"
          style={{ background: "#F5821F" }}
        >
          <Plus size={16} /> New Payment
        </Button>
      </div>

      {/* Filter bar */}
          <div className="flex flex-wrap items-center gap-3">
            <div className="flex gap-1.5">
              {PAYMENT_TYPES.map(t => (
                <button
                  key={t.key}
                  onClick={() => setTypeFilter(f => f === t.key ? "" : t.key)}
                  className={`px-2.5 py-1 rounded-full text-xs font-medium border transition-all ${
                    typeFilter === t.key
                      ? "border-[#F5821F] text-[#F5821F] bg-[#FEF0E3]"
                      : "border-stone-200 text-stone-500 hover:border-stone-400"
                  }`}
                >
                  {t.label}
                </button>
              ))}
            </div>
            <Input type="date" value={dateFrom} onChange={e => setDateFrom(e.target.value)}
              className="h-9 text-sm w-36" />
            <span className="text-stone-400 text-sm">—</span>
            <Input type="date" value={dateTo} onChange={e => setDateTo(e.target.value)}
              className="h-9 text-sm w-36" />
          </div>

          <div className="rounded-xl border border-stone-200 overflow-x-auto">
            <table className="w-full min-w-[700px] text-sm">
              <thead className="bg-stone-50 border-b border-stone-200">
                <tr>
                  <SortableTh col="payRef" sortBy={sortBy} sortDir={sortDir} onSort={onSort} className="text-left px-4 py-3 text-xs font-semibold text-stone-500 uppercase tracking-wide">PAY Ref</SortableTh>
                  <SortableTh col="paymentDate" sortBy={sortBy} sortDir={sortDir} onSort={onSort} className="text-left px-4 py-3 text-xs font-semibold text-stone-500 uppercase tracking-wide">Date</SortableTh>
                  <SortableTh col="paymentType" sortBy={sortBy} sortDir={sortDir} onSort={onSort} className="text-left px-4 py-3 text-xs font-semibold text-stone-500 uppercase tracking-wide">Type</SortableTh>
                  <SortableTh col="fromName" sortBy={sortBy} sortDir={sortDir} onSort={onSort} className="text-left px-4 py-3 text-xs font-semibold text-stone-500 uppercase tracking-wide">From</SortableTh>
                  <SortableTh col="toName" sortBy={sortBy} sortDir={sortDir} onSort={onSort} className="text-left px-4 py-3 text-xs font-semibold text-stone-500 uppercase tracking-wide">To</SortableTh>
                  <SortableTh col="totalAmount" sortBy={sortBy} sortDir={sortDir} onSort={onSort} className="text-left px-4 py-3 text-xs font-semibold text-stone-500 uppercase tracking-wide">Amount</SortableTh>
                  <SortableTh col="status" sortBy={sortBy} sortDir={sortDir} onSort={onSort} className="text-left px-4 py-3 text-xs font-semibold text-stone-500 uppercase tracking-wide">Status</SortableTh>
                  <th className="text-left px-4 py-3 text-xs font-semibold text-stone-500 uppercase tracking-wide">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-stone-100">
                {paymentsLoading && (
                  <tr><td colSpan={8} className="text-center py-12 text-stone-400 text-sm">Loading…</td></tr>
                )}
                {!paymentsLoading && payments.length === 0 && (
                  <tr><td colSpan={8} className="text-center py-12 text-stone-400 text-sm">No payments yet</td></tr>
                )}
                {sortedPayments.map(p => {
                  const notesObj = parseNotes(p.notes);
                  const statusStyle = STATUS_STYLE[p.status] ?? STATUS_STYLE.Active;
                  const typeBg = TYPE_STYLE[p.paymentType] ?? "#F4F3F1";
                  return (
                    <tr key={p.id} className={`hover:bg-[#FEF0E3] cursor-pointer transition-colors ${p.status === "Void" ? "opacity-50" : ""}`} onClick={() => navigate(`/admin/accounting/payments/${p.id}`)}>
                      <td className="px-4 py-3 font-mono text-xs text-stone-500">{p.paymentRef ?? "—"}</td>
                      <td className="px-4 py-3 text-stone-700">{fmtDate(p.paymentDate)}</td>
                      <td className="px-4 py-3">
                        <span className="px-2 py-0.5 rounded text-xs font-medium" style={{ background: typeBg, color: "#57534E" }}>
                          {PAYMENT_TYPES.find(t => t.key === p.paymentType)?.label ?? p.paymentType}
                        </span>
                      </td>
                      <td className="px-4 py-3 text-xs">
                        {notesObj.receivedFromName && p.receivedFrom ? (
                          <button
                            onClick={() => navigate(`/admin/crm/accounts/${p.receivedFrom}`)}
                            className="flex items-center gap-1 text-[#F5821F] hover:underline font-medium"
                          >
                            {notesObj.receivedFromName}
                            <ExternalLink size={9} className="shrink-0" />
                          </button>
                        ) : (
                          <span className="text-stone-400">—</span>
                        )}
                      </td>
                      <td className="px-4 py-3 text-xs">
                        {notesObj.paidToName && p.paidTo ? (
                          <button
                            onClick={() => navigate(`/admin/crm/accounts/${p.paidTo}`)}
                            className="flex items-center gap-1 text-[#F5821F] hover:underline font-medium"
                          >
                            {notesObj.paidToName}
                            <ExternalLink size={9} className="shrink-0" />
                          </button>
                        ) : (
                          <span className="text-stone-400">—</span>
                        )}
                      </td>
                      <td className="px-4 py-3 font-medium text-stone-800">{fmtAmt(p.totalAmount)}</td>
                      <td className="px-4 py-3">
                        <span className="px-2.5 py-0.5 rounded-full text-xs font-medium"
                          style={{ background: statusStyle.bg, color: statusStyle.text }}>
                          {p.status}
                        </span>
                      </td>
                      <td className="px-4 py-3">
                        <VoidAction paymentId={p.id} status={p.status} isSuperAdmin={isSuperAdmin} />
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>

      {showCreate && <CreateSheet onClose={() => setShowCreate(false)} />}
    </div>
  );
}
