import { db } from "@workspace/db";
import {
  contracts, applications, packages, packageProducts, products,
  contractFinanceItems, userLedger, invoices, receipts, notifications,
} from "@workspace/db/schema";
import { eq, and, count } from "drizzle-orm";

// ── Product type → cost center / category mapping ──────────────────────────
const PRODUCT_TYPE_MAP: Record<string, { category: string; costCenter: string }> = {
  institute:  { category: "cc_institute",  costCenter: "CC-INSTITUTE"  },
  hotel:      { category: "cc_hotel",      costCenter: "CC-HOTEL"      },
  pickup:     { category: "cc_pickup",     costCenter: "CC-PICKUP"     },
  tour:       { category: "cc_tour",       costCenter: "CC-TOUR"       },
  settlement: { category: "cc_settlement", costCenter: "CC-SETTLEMENT" },
};

function productTypeToMapping(type: string): { category: string; costCenter: string } {
  return PRODUCT_TYPE_MAP[type.toLowerCase()] ?? { category: "cc_misc", costCenter: "CC-MISC" };
}

function calcCommission(totalFee: number, pkg: any): number {
  if (!pkg.agentCommissionType) return 0;
  if (pkg.agentCommissionType === "percentage") {
    return totalFee * (parseFloat(pkg.agentCommissionRate ?? "0") / 100);
  }
  if (pkg.agentCommissionType === "fixed") {
    return parseFloat(pkg.agentCommissionFixed ?? "0");
  }
  return 0;
}

// ── Receipt number: RCP-{YYYY}-{0001} ─────────────────────────────────────
async function generateReceiptNumber(): Promise<string> {
  const year = new Date().getFullYear();
  const [countResult] = await db.select({ count: count() }).from(receipts);
  const seq = String(Number(countResult.count) + 1).padStart(4, "0");
  return `RCP-${year}-${seq}`;
}

// ═══════════════════════════════════════════════════════════════════════════
//  financeAutoGenerate
// ═══════════════════════════════════════════════════════════════════════════
export async function financeAutoGenerate(contractId: string): Promise<{ created: number }> {
  // Idempotency: skip if items already exist
  const existing = await db
    .select({ count: count() })
    .from(contractFinanceItems)
    .where(and(eq(contractFinanceItems.contractId, contractId), eq(contractFinanceItems.isDeleted, false)));
  if (Number(existing[0]?.count ?? 0) > 0) {
    return { created: 0 };
  }

  // Load contract + application + package
  const [contract] = await db.select().from(contracts).where(eq(contracts.id, contractId)).limit(1);
  if (!contract) throw new Error(`Contract ${contractId} not found`);

  let application: any = null;
  let pkg: any = null;
  let pkgProducts: Array<{ product: any; link: any }> = [];

  if (contract.applicationId) {
    const [app] = await db.select().from(applications).where(eq(applications.id, contract.applicationId)).limit(1);
    application = app ?? null;
  }

  if (application?.packageId) {
    const [p] = await db.select().from(packages).where(eq(packages.id, application.packageId)).limit(1);
    pkg = p ?? null;
  }

  if (pkg) {
    const ppRows = await db
      .select({ link: packageProducts, product: products })
      .from(packageProducts)
      .leftJoin(products, eq(packageProducts.productId, products.id))
      .where(eq(packageProducts.packageId, pkg.id));
    pkgProducts = ppRows.filter(r => r.product !== null) as Array<{ product: any; link: any }>;
  }

  const currency = contract.currency ?? "AUD";
  const totalFee = parseFloat(contract.totalAmount ?? "0");
  const agentId: string | null = application?.agentId ?? null;
  const hasAgent = !!agentId;

  const commissionAmount = pkg ? calcCommission(totalFee, pkg) : 0;
  const netCampRevenue = totalFee - commissionAmount;

  const itemsToInsert: any[] = [];

  // ── RECEIVABLE: Client Invoice ─────────────────────────────────────────
  itemsToInsert.push({
    contractId,
    itemType: "receivable",
    itemCategory: "client_invoice",
    costCenter: hasAgent ? "RC-CAMP" : "RC-DIRECT",
    label: "Client Invoice",
    estimatedAmount: String(totalFee.toFixed(2)),
    currency,
    status: "pending",
    isAutoGenerated: true,
    isDeleted: false,
  });

  // ── RECEIVABLE: Agent Invoice (if agent linked) ────────────────────────
  if (hasAgent && pkg) {
    itemsToInsert.push({
      contractId,
      itemType: "receivable",
      itemCategory: "agent_invoice",
      costCenter: "RC-CAMP",
      label: "Agent Invoice (Net of Commission)",
      linkedAgentId: agentId,
      estimatedAmount: String(netCampRevenue.toFixed(2)),
      currency,
      commissionType: pkg.agentCommissionType ?? null,
      commissionRate: pkg.agentCommissionRate ?? null,
      commissionFixed: pkg.agentCommissionFixed ?? null,
      status: "pending",
      isAutoGenerated: true,
      isDeleted: false,
    });
  }

  // ── PAYABLE: One per product ───────────────────────────────────────────
  for (const { product, link } of pkgProducts) {
    const { category, costCenter } = productTypeToMapping(product.productType ?? "");
    const unitPrice = parseFloat(link.unitPrice ?? product.cost ?? "0");
    const qty = link.quantity ?? 1;
    itemsToInsert.push({
      contractId,
      itemType: "payable",
      itemCategory: category,
      costCenter,
      label: product.productName,
      linkedProductId: product.id,
      linkedPartnerId: product.providerAccountId ?? null,
      estimatedAmount: String((unitPrice * qty).toFixed(2)),
      currency,
      status: "pending",
      isAutoGenerated: true,
      isDeleted: false,
    });
  }

  // ── PAYABLE: Agent Commission ──────────────────────────────────────────
  if (hasAgent && commissionAmount > 0 && pkg) {
    itemsToInsert.push({
      contractId,
      itemType: "payable",
      itemCategory: "cc_agent",
      costCenter: "CC-AGENT",
      label: "Agent Commission",
      linkedAgentId: agentId,
      estimatedAmount: String(commissionAmount.toFixed(2)),
      currency,
      commissionType: pkg.agentCommissionType ?? null,
      commissionRate: pkg.agentCommissionRate ?? null,
      commissionFixed: pkg.agentCommissionFixed ?? null,
      status: "pending",
      isAutoGenerated: true,
      isDeleted: false,
    });
  }

  if (itemsToInsert.length > 0) {
    await db.insert(contractFinanceItems).values(itemsToInsert);
  }

  return { created: itemsToInsert.length };
}

// ═══════════════════════════════════════════════════════════════════════════
//  buildFinanceSummary — grouped response for GET /contracts/:id/finance
// ═══════════════════════════════════════════════════════════════════════════
export async function buildFinanceSummary(contractId: string) {
  const all = await db
    .select()
    .from(contractFinanceItems)
    .where(and(eq(contractFinanceItems.contractId, contractId), eq(contractFinanceItems.isDeleted, false)));

  const receivable = all.filter(i => i.itemType === "receivable");
  const payable    = all.filter(i => i.itemType === "payable");

  const sumOf = (rows: any[], field = "estimatedAmount") =>
    rows.reduce((acc, r) => acc + parseFloat(r[field] ?? "0"), 0);
  const paidSumOf = (rows: any[]) =>
    rows.filter(r => r.status === "paid").reduce((acc, r) => acc + parseFloat(r.actualAmount ?? r.estimatedAmount ?? "0"), 0);

  const clientInvoice = receivable.find(i => i.itemCategory === "client_invoice");
  const agentInvoice  = receivable.find(i => i.itemCategory === "agent_invoice");
  const agentCost     = payable.find(i => i.itemCategory === "cc_agent");

  const totalFee         = parseFloat(clientInvoice?.estimatedAmount ?? "0");
  const agentCommission  = parseFloat(agentCost?.estimatedAmount ?? "0");
  const netCampRevenue   = totalFee - agentCommission;
  const totalPayable     = sumOf(payable);
  const grossProfit      = netCampRevenue - totalPayable;

  // Cost center breakdown
  const ccMap: Record<string, number> = {};
  for (const row of payable) {
    const cc = row.costCenter ?? "CC-MISC";
    ccMap[cc] = (ccMap[cc] ?? 0) + parseFloat(row.estimatedAmount ?? "0");
  }
  const CC_LABELS: Record<string, string> = {
    "CC-AGENT": "Agent Commission", "CC-INSTITUTE": "Institute",
    "CC-HOTEL": "Hotel", "CC-PICKUP": "Pickup/Transfer",
    "CC-TOUR": "Tours", "CC-SETTLEMENT": "Settlement", "CC-MISC": "Miscellaneous",
  };
  const costCenterBreakdown = Object.entries(ccMap).map(([center, amount]) => ({
    center, label: CC_LABELS[center] ?? center, amount,
  }));

  const PAID_STATUSES = ["paid"];
  const PENDING_STATUSES = ["pending", "invoiced", "partial", "overdue"];

  const receivablePaid    = sumOf(receivable.filter(r => PAID_STATUSES.includes(r.status)), "actualAmount");
  const receivablePending = sumOf(receivable.filter(r => PENDING_STATUSES.includes(r.status)));
  const payablePaid       = sumOf(payable.filter(r => PAID_STATUSES.includes(r.status)), "actualAmount");
  const payablePending    = sumOf(payable.filter(r => PENDING_STATUSES.includes(r.status)));

  return {
    receivable,
    payable,
    summary: {
      totalFee,
      agentCommission,
      netCampRevenue,
      totalPayable,
      grossProfit,
      costCenterBreakdown,
      receivablePaid,
      receivablePending,
      payablePaid,
      payablePending,
    },
  };
}

// ═══════════════════════════════════════════════════════════════════════════
//  confirmPayment — POST /finance/items/:itemId/confirm-payment
// ═══════════════════════════════════════════════════════════════════════════
export async function confirmPayment(
  itemId: string,
  payload: {
    actualAmount: number;
    paidDate: string;
    referenceNo?: string;
    paymentMethod?: string;
    notes?: string;
  },
  actingUserId: string,
) {
  // 1. Load item
  const [item] = await db
    .select()
    .from(contractFinanceItems)
    .where(eq(contractFinanceItems.id, itemId))
    .limit(1);
  if (!item) throw new Error("Finance item not found");

  // 2. Update finance item → paid
  await db.update(contractFinanceItems).set({
    status: "paid",
    actualAmount: String(payload.actualAmount),
    paidDate: payload.paidDate,
    notes: payload.notes ?? item.notes,
    updatedAt: new Date(),
  }).where(eq(contractFinanceItems.id, itemId));

  // 3. Create user_ledger entry
  const entryType = item.itemType === "receivable" ? "credit" : "debit";
  await db.insert(userLedger).values({
    contractId: item.contractId,
    financeItemId: itemId,
    userId: actingUserId,
    entryType,
    costCenter: item.costCenter ?? undefined,
    amount: String(payload.actualAmount),
    currency: item.currency ?? "AUD",
    description: `Payment confirmed: ${item.label}`,
    referenceType: "invoice",
    transactionDate: payload.paidDate,
    status: "confirmed",
    createdBy: actingUserId,
  });

  // 4. Update linked invoice if financeItemId is set on an invoice
  const linkedInvoices = await db
    .select()
    .from(invoices)
    .where(eq(invoices.financeItemId, itemId));
  for (const inv of linkedInvoices) {
    await db.update(invoices).set({ status: "paid", paidAt: new Date(), updatedAt: new Date() })
      .where(eq(invoices.id, inv.id));
  }

  // 5. Auto-generate receipt for receivable items
  let newReceipt: any = null;
  if (
    item.itemType === "receivable" &&
    (item.itemCategory === "client_invoice" || item.itemCategory === "agent_invoice")
  ) {
    const receiptNumber = await generateReceiptNumber();
    const payerId = item.itemCategory === "agent_invoice"
      ? (item.linkedAgentId ?? actingUserId)
      : actingUserId;

    const [receipt] = await db.insert(receipts).values({
      receiptNumber,
      payerId,
      amount: String(payload.actualAmount),
      currency: item.currency ?? "AUD",
      paymentMethod: payload.paymentMethod ?? null,
      receiptDate: payload.paidDate,
      status: "confirmed",
      notes: payload.notes ?? null,
      financeItemId: itemId,
      confirmedBy: actingUserId,
      confirmedAt: new Date(),
    }).returning();
    newReceipt = receipt;

    // In-app notification
    try {
      await db.insert(notifications).values({
        userId: payerId,
        type: "receipt_generated",
        title: `Payment Confirmed — ${receiptNumber}`,
        message: `Your payment of ${item.currency ?? "AUD"} ${payload.actualAmount} has been confirmed. Receipt: ${receiptNumber}`,
        referenceType: "receipt",
        referenceId: receipt.id,
        isRead: false,
      });
    } catch (e: any) {
      console.error("Notification insert failed:", e.message);
    }
  }

  return { item, receipt: newReceipt };
}
