import { Router } from "express";
import { db } from "@workspace/db";
import {
  paymentHeaders, paymentLines, journalEntries,
  chartOfAccounts, contractProducts, contracts,
  transactions, accounts,
} from "@workspace/db/schema";
import { eq, and, gte, lte, inArray, ilike, asc, desc, sql, SQL } from "drizzle-orm";
import { generateTaxInvoice } from "../services/taxInvoiceService.js";
import { authenticate } from "../middleware/authenticate.js";
import { requireRole } from "../middleware/requireRole.js";

const router = Router();
const STAFF_ROLES  = ["super_admin", "admin", "camp_coordinator"];
const ADMIN_ROLES  = ["super_admin", "admin"];

// ─── JE mapping ─────────────────────────────────────────────────────────────
const JE_MAP: Record<string, { debit: string; credit: string }> = {
  trust_receipt:      { debit: "1200", credit: "1300" },
  trust_transfer:     { debit: "2100", credit: "1200" },
  commission:         { debit: "1100", credit: "3100" },
  direct:             { debit: "4700", credit: "1100" },
  service_fee_camp:   { debit: "1100", credit: "3500" },
  camp_tour_ap:       { debit: "4600", credit: "1100" },
  camp_institute_ap:  { debit: "4700", credit: "1100" },
};

function genPayRef(): string {
  return "PAY-" + Date.now().toString(36).toUpperCase().padStart(8, "0");
}

function userId(req: any): string {
  return req.user?.id ?? "00000000-0000-0000-0000-000000000000";
}

// ─── GET /api/accounting/journal-entries ────────────────────────────────────
router.get(
  "/accounting/journal-entries",
  authenticate,
  requireRole(...STAFF_ROLES),
  async (req, res) => {
    try {
      const rows = await db
        .select({
          id:              journalEntries.id,
          entryDate:       journalEntries.entryDate,
          paymentHeaderId: journalEntries.paymentHeaderId,
          debitCoa:        journalEntries.debitCoa,
          creditCoa:       journalEntries.creditCoa,
          amount:          journalEntries.amount,
          entryType:       journalEntries.entryType,
          contractId:      journalEntries.contractId,
          autoGenerated:   journalEntries.autoGenerated,
          createdOn:       journalEntries.createdOn,
          paymentRef:      paymentHeaders.paymentRef,
          paymentStatus:   paymentHeaders.status,
        })
        .from(journalEntries)
        .leftJoin(paymentHeaders, eq(journalEntries.paymentHeaderId, paymentHeaders.id))
        .orderBy(desc(journalEntries.createdOn))
        .limit(200);

      // Attach CoA names
      const allCodes = [...new Set(rows.flatMap(r => [r.debitCoa, r.creditCoa]))];
      const coaRows = allCodes.length
        ? await db.select({ code: chartOfAccounts.code, name: chartOfAccounts.name })
            .from(chartOfAccounts)
            .where(inArray(chartOfAccounts.code, allCodes))
        : [];
      const coaMap = Object.fromEntries(coaRows.map(c => [c.code, c.name]));

      return res.json({
        data: rows.map(r => ({
          ...r,
          debitCoaName:  coaMap[r.debitCoa]  ?? r.debitCoa,
          creditCoaName: coaMap[r.creditCoa] ?? r.creditCoa,
        })),
      });
    } catch (err) {
      console.error("[GET /api/accounting/journal-entries]", err);
      return res.status(500).json({ error: "Internal server error" });
    }
  }
);

// ─── GET /api/accounting/payments ───────────────────────────────────────────
router.get(
  "/accounting/payments",
  authenticate,
  requireRole(...STAFF_ROLES),
  async (req, res) => {
    try {
      const { paymentType, status, date_from, date_to } = req.query as Record<string, string>;
      const conds: SQL[] = [];
      if (paymentType) conds.push(eq(paymentHeaders.paymentType, paymentType));
      if (status)      conds.push(eq(paymentHeaders.status, status));
      if (date_from)   conds.push(gte(paymentHeaders.paymentDate, date_from));
      if (date_to)     conds.push(lte(paymentHeaders.paymentDate, date_to));
      const where = conds.length ? and(...conds) : undefined;

      const rows = await db
        .select()
        .from(paymentHeaders)
        .where(where)
        .orderBy(desc(paymentHeaders.createdOn))
        .limit(200);

      return res.json({ data: rows });
    } catch (err) {
      console.error("[GET /api/accounting/payments]", err);
      return res.status(500).json({ error: "Internal server error" });
    }
  }
);

// ─── GET /api/accounting/payments/:id ───────────────────────────────────────
router.get(
  "/accounting/payments/:id",
  authenticate,
  requireRole(...STAFF_ROLES),
  async (req, res) => {
    try {
      const [header] = await db
        .select()
        .from(paymentHeaders)
        .where(eq(paymentHeaders.id, req.params.id));
      if (!header) return res.status(404).json({ error: "Payment not found" });

      const lines = await db
        .select()
        .from(paymentLines)
        .where(eq(paymentLines.paymentHeaderId, req.params.id));

      const entries = await db
        .select()
        .from(journalEntries)
        .where(eq(journalEntries.paymentHeaderId, req.params.id));

      return res.json({ ...header, lines, journalEntries: entries });
    } catch (err) {
      console.error("[GET /api/accounting/payments/:id]", err);
      return res.status(500).json({ error: "Internal server error" });
    }
  }
);

// ─── POST /api/accounting/payments ──────────────────────────────────────────
router.post(
  "/accounting/payments",
  authenticate,
  requireRole(...STAFF_ROLES),
  async (req, res) => {
    try {
      const {
        contractId,
        invoiceId,
        paymentDate, paymentMethod, paymentType,
        bankReference, notes,
        receivedFromName, paidToName,
        receivedFromId, paidToId,
        lines: lineItems = [],
      } = req.body;

      if (!paymentDate || !paymentType) {
        return res.status(400).json({ error: "paymentDate and paymentType are required" });
      }

      const jeMap = JE_MAP[paymentType];
      if (!jeMap) {
        return res.status(400).json({ error: `Unknown paymentType: ${paymentType}` });
      }

      // Total from lines (server-side calculation)
      const totalAmount = (lineItems as any[]).reduce(
        (sum: number, l: any) => sum + Number(l.amount ?? 0), 0
      );

      // Store receivedFromName/paidToName in notes JSON
      const notesPayload = JSON.stringify({
        receivedFromName: receivedFromName ?? null,
        paidToName: paidToName ?? null,
        notes: notes ?? null,
      });

      const result = await db.transaction(async (tx) => {
        // 1. Create payment header
        const [header] = await tx.insert(paymentHeaders).values({
          paymentRef:    genPayRef(),
          contractId:    contractId ?? null,
          invoiceId:     invoiceId && invoiceId.trim() ? invoiceId : null,
          paymentDate,
          totalAmount:   String(totalAmount.toFixed(2)),
          currency:      "AUD",
          paymentMethod: paymentMethod ?? null,
          paymentType,
          receivedFrom:  receivedFromId ?? null,
          paidTo:        paidToId ?? null,
          bankReference: bankReference ?? null,
          notes:         notesPayload,
          createdBy:     userId(req),
          status:        "Active",
        }).returning();

        // 2. Insert payment lines
        const insertedLines: any[] = [];
        if (Array.isArray(lineItems) && lineItems.length > 0) {
          const vals = lineItems.map((l: any) => ({
            paymentHeaderId:   header.id,
            contractProductId: l.contractProductId ?? null,
            coaCode:           l.coaCode ?? null,
            splitType:         l.splitType ?? null,
            amount:            String(Number(l.amount ?? 0).toFixed(2)),
            description:       l.description ?? null,
          }));
          const lines = await tx.insert(paymentLines).values(vals).returning();
          insertedLines.push(...lines);
        }

        // 3. Update AR/AP status on linked contract_products
        const cpIds = (lineItems as any[])
          .map((l: any) => l.contractProductId)
          .filter(Boolean);

        if (cpIds.length > 0) {
          if (paymentType === "trust_receipt") {
            await tx
              .update(contractProducts)
              .set({ arStatus: "paid" })
              .where(inArray(contractProducts.id, cpIds));
          } else if (paymentType === "trust_transfer") {
            await tx
              .update(contractProducts)
              .set({ apStatus: "paid" })
              .where(inArray(contractProducts.id, cpIds));
          }
        }

        // 4. Auto-generate journal entry
        const [je] = await tx.insert(journalEntries).values({
          entryDate:       paymentDate,
          paymentHeaderId: header.id,
          debitCoa:        jeMap.debit,
          creditCoa:       jeMap.credit,
          amount:          String(totalAmount.toFixed(2)),
          description:     `Auto-generated JE for ${paymentType} — ${header.paymentRef}`,
          entryType:       paymentType,
          autoGenerated:   true,
          createdBy:       userId(req),
        }).returning();

        return { header, lines: insertedLines, journalEntry: je };
      });

      // === BRIDGE: auto-create transaction record ===
      try {
        // trust_receipt (고객 입금) → transactionType: 'payment_received', creditAmount 설정
        // trust_transfer (송금)     → transactionType: 'bank_transfer',    amount 설정
        // 그 외 타입                 → transactionType: paymentType,        amount 설정
        const txType =
          paymentType === "trust_receipt"  ? "payment_received" :
          paymentType === "trust_transfer" ? "bank_transfer"    :
          paymentType;

        const firstLine = (lineItems as any[])[0];

        await db.insert(transactions).values({
          transactionType:  txType,
          transactionDate:  paymentDate,
          amount:           String(totalAmount.toFixed(2)),
          creditAmount:     paymentType === "trust_receipt"
                              ? String(totalAmount.toFixed(2))
                              : null,
          currency:         "AUD",
          description:      `${paymentType} — ${result.header.paymentRef} — ${totalAmount.toFixed(2)}`,
          bankReference:    bankReference ?? null,
          accountId:        receivedFromId ?? paidToId ?? null,
          paymentInfoId:    result.header.id,
          contractId:       firstLine?.contractId ?? null,
          invoiceId:        firstLine?.invoiceId  ?? null,
          createdBy:        userId(req),
          status:           "Active",
        });
      } catch (bridgeError) {
        // 브릿지 실패해도 payment_header 저장은 성공으로 처리
        console.error("[Bridge] Failed to create transaction record:", bridgeError);
      }
      // === END BRIDGE ===

      // ── Tax Invoice auto-generation (post-transaction, non-blocking) ──────
      if (paymentType === "trust_transfer") {
        const cpIds = (lineItems as any[])
          .map((l: any) => l.contractProductId)
          .filter(Boolean) as string[];

        if (cpIds.length > 0) {
          const cpRows = await db
            .select({ id: contractProducts.id, remittanceMethod: contractProducts.remittanceMethod })
            .from(contractProducts)
            .where(inArray(contractProducts.id, cpIds));

          for (const cp of cpRows) {
            if (!cp.remittanceMethod) continue;
            generateTaxInvoice(cp.id, result.header.id, userId(req)).catch((err) => {
              console.error(`[TaxInvoice] Generation failed for CP ${cp.id}:`, String(err));
            });
          }
        }
      }

      return res.status(201).json(result);
    } catch (err) {
      console.error("[POST /api/accounting/payments]", err);
      return res.status(500).json({ error: "Internal server error" });
    }
  }
);

// ─── PATCH /api/accounting/payments/:id/void ────────────────────────────────
router.patch(
  "/accounting/payments/:id/void",
  authenticate,
  requireRole(...ADMIN_ROLES),
  async (req, res) => {
    try {
      const [existing] = await db
        .select({ id: paymentHeaders.id, status: paymentHeaders.status })
        .from(paymentHeaders)
        .where(eq(paymentHeaders.id, req.params.id));

      if (!existing) return res.status(404).json({ error: "Payment not found" });
      if (existing.status === "Void") return res.status(400).json({ error: "Payment already voided" });

      const [updated] = await db
        .update(paymentHeaders)
        .set({ status: "Void", modifiedOn: new Date() })
        .where(eq(paymentHeaders.id, req.params.id))
        .returning();

      // Cascade: also deactivate any linked transaction records
      try {
        await db
          .update(transactions)
          .set({ status: "Inactive" })
          .where(and(
            eq(transactions.paymentInfoId, req.params.id),
            eq(transactions.status, "Active"),
          ));
      } catch (cascadeErr) {
        console.error("[PATCH /payments/:id/void] cascade transaction deactivation failed:", cascadeErr);
      }

      return res.json(updated);
    } catch (err) {
      console.error("[PATCH /api/accounting/payments/:id/void]", err);
      return res.status(500).json({ error: "Internal server error" });
    }
  }
);

// ─── LOOKUP: accounts search ─────────────────────────────────────────────────
router.get("/accounting/payments-lookup/accounts", authenticate, async (req, res) => {
  try {
    const { search = "" } = req.query as Record<string, string>;
    const conds: SQL[] = [];
    if (search) conds.push(ilike(accounts.name, `%${search}%`));
    const rows = await db
      .select({ id: accounts.id, name: accounts.name, accountType: accounts.accountType })
      .from(accounts)
      .where(conds.length ? and(...conds) : undefined)
      .orderBy(asc(accounts.name))
      .limit(20);
    return res.json(rows);
  } catch (err) {
    console.error("[GET /accounting/payments-lookup/accounts]", err);
    return res.status(500).json({ error: "Internal server error" });
  }
});

// ─── LOOKUP: contract search ──────────────────────────────────────────────────
router.get("/accounting/payments-lookup/contracts", authenticate, async (req, res) => {
  try {
    const { search = "" } = req.query as Record<string, string>;
    const r = (x: any) => x.rows ?? (x as any[]);
    const rows = await db.execute(sql`
      SELECT c.id, c.contract_number, c.student_name, c.status,
             a.id   AS account_id,
             a.name AS account_name
      FROM contracts c
      LEFT JOIN accounts a ON a.id = c.account_id
      WHERE c.status IN ('active', 'signed')
        AND (
          ${search} = ''
          OR c.contract_number ILIKE ${'%' + search + '%'}
          OR c.student_name    ILIKE ${'%' + search + '%'}
          OR a.name            ILIKE ${'%' + search + '%'}
        )
      ORDER BY c.created_at DESC
      LIMIT 20
    `);
    return res.json(r(rows));
  } catch (err) {
    console.error("[GET /accounting/payments-lookup/contracts]", err);
    return res.status(500).json({ error: "Internal server error" });
  }
});

// ─── LOOKUP: contract products ────────────────────────────────────────────────
router.get("/accounting/payments-lookup/contracts/:id/products", authenticate, async (req, res) => {
  try {
    const r = (x: any) => x.rows ?? (x as any[]);
    const rows = await db.execute(sql`
      SELECT id,
             COALESCE(name, product_name) AS name,
             ar_amount, ar_status,
             ap_amount, ap_status,
             service_module_type
      FROM contract_products
      WHERE contract_id = ${req.params.id}::uuid
      ORDER BY COALESCE(sort_index, 0), created_at
    `);
    return res.json(r(rows));
  } catch (err) {
    console.error("[GET /accounting/payments-lookup/contracts/:id/products]", err);
    return res.status(500).json({ error: "Internal server error" });
  }
});

// ─── PAYMENTS BY CONTRACT ─────────────────────────────────────────────────────
router.get("/accounting/payments/by-contract/:contractId", authenticate, async (req, res) => {
  try {
    const { contractId } = req.params;
    const r = (x: any) => x.rows ?? (x as any[]);
    const rows = await db.execute(sql`
      SELECT
        ph.id,
        ph.payment_ref,
        ph.payment_date,
        ph.total_amount,
        ph.payment_type,
        ph.payment_method,
        ph.bank_reference,
        ph.status,
        ph.notes,
        ph.received_from,
        ph.paid_to,
        rf.name  AS received_from_name,
        pt.name  AS paid_to_name,
        pl.id    AS line_id,
        pl.amount          AS line_amount,
        pl.split_type,
        pl.description     AS line_description,
        cp.name AS product_name,
        cp.ar_status,
        cp.ap_status
      FROM payment_lines pl
      JOIN payment_headers ph ON ph.id = pl.payment_header_id
      JOIN contract_products cp ON cp.id = pl.contract_product_id
      LEFT JOIN accounts rf ON rf.id = ph.received_from
      LEFT JOIN accounts pt ON pt.id = ph.paid_to
      WHERE cp.contract_id = ${contractId}::uuid
        AND ph.status != 'Void'
      ORDER BY ph.payment_date DESC, ph.created_on DESC
    `);
    return res.json(r(rows));
  } catch (err) {
    console.error("[GET /api/accounting/payments/by-contract]", err);
    return res.status(500).json({ error: "Internal server error" });
  }
});

// ─── LEDGER BY ACCOUNT ────────────────────────────────────────────────────────
router.get("/accounting/ledger/by-account/:accountId", authenticate, async (req, res) => {
  try {
    const { accountId } = req.params;
    const r = (x: any) => x.rows ?? (x as any[]);
    const rows = await db.execute(sql`
      SELECT
        'payment' AS source,
        ph.id,
        ph.payment_ref      AS ref,
        ph.payment_date     AS entry_date,
        ph.total_amount     AS amount,
        ph.payment_type     AS type,
        ph.payment_method   AS method,
        ph.status,
        ph.bank_reference,
        ph.notes,
        CASE
          WHEN ph.received_from = ${accountId}::uuid THEN 'received'
          ELSE 'paid'
        END AS direction,
        rf.name AS received_from_name,
        pt.name AS paid_to_name
      FROM payment_headers ph
      LEFT JOIN accounts rf ON rf.id = ph.received_from
      LEFT JOIN accounts pt ON pt.id = ph.paid_to
      WHERE (ph.received_from = ${accountId}::uuid OR ph.paid_to = ${accountId}::uuid)
        AND ph.status != 'Void'

      UNION ALL

      SELECT
        'transaction' AS source,
        t.id,
        COALESCE(t.bank_reference, t.id::text) AS ref,
        t.transaction_date  AS entry_date,
        COALESCE(t.credit_amount, t.amount)    AS amount,
        t.transaction_type  AS type,
        NULL                AS method,
        t.status,
        t.bank_reference,
        t.description       AS notes,
        'transaction'       AS direction,
        NULL                AS received_from_name,
        NULL                AS paid_to_name
      FROM transactions t
      WHERE t.account_id = ${accountId}::uuid

      ORDER BY entry_date DESC NULLS LAST
      LIMIT 200
    `);
    return res.json(r(rows));
  } catch (err) {
    console.error("[GET /api/accounting/ledger/by-account]", err);
    return res.status(500).json({ error: "Internal server error" });
  }
});

export default router;
