import { Router } from "express";
import { db } from "@workspace/db";
import {
  paymentHeaders, paymentLines, journalEntries,
  chartOfAccounts, contractProducts, contracts,
  transactions, accounts,
} from "@workspace/db/schema";
import { eq, and, gte, lte, inArray, ilike, asc, desc, sql, SQL } from "drizzle-orm";
import { generateTaxInvoice } from "../services/taxInvoiceService.js";
import { createJournalEntriesForPaymentLine } from "../services/journalEntryService.js";
import { authenticate } from "../middleware/authenticate.js";
import { requireRole } from "../middleware/requireRole.js";
import {
  resolvePackageGroupIdFromContractId,
  assertFinanceDelegation,
} from "../lib/financeDelegationGuard.js";

const router = Router();
const STAFF_ROLES  = ["super_admin", "admin", "finance", "admission", "team_manager", "camp_coordinator"];
const ADMIN_ROLES  = ["super_admin", "admin"];

// DR/CR mapping is centralized in services/journalEntryService.ts.
// Do not duplicate it here — see FINANCE_SYSTEM_GUIDE.md §4.2.

function genPayRef(): string {
  return "PAY-" + Date.now().toString(36).toUpperCase().padStart(8, "0");
}

function userId(req: any): string {
  return req.user?.id ?? "00000000-0000-0000-0000-000000000000";
}

function requireTenant(req: any, res: any): string | null {
  const tid = req.tenantId as string | undefined;
  if (!tid) {
    res.status(400).json({ error: "Tenant context required" });
    return null;
  }
  return tid;
}

// ─── GET /api/accounting/journal-entries ────────────────────────────────────
router.get(
  "/accounting/journal-entries",
  authenticate,
  requireRole(...STAFF_ROLES),
  async (req, res) => {
    try {
      const tenantId = requireTenant(req, res);
      if (!tenantId) return;
      const rows = await db
        .select({
          id:              journalEntries.id,
          entryDate:       journalEntries.entryDate,
          paymentHeaderId: journalEntries.paymentHeaderId,
          debitCoa:        journalEntries.debitCoa,
          creditCoa:       journalEntries.creditCoa,
          amount:          journalEntries.amount,
          entryType:       journalEntries.entryType,
          contractId:      journalEntries.contractId,
          autoGenerated:   journalEntries.autoGenerated,
          createdOn:       journalEntries.createdOn,
          paymentRef:      paymentHeaders.paymentRef,
          paymentStatus:   paymentHeaders.status,
        })
        .from(journalEntries)
        .innerJoin(
          paymentHeaders,
          and(
            eq(journalEntries.paymentHeaderId, paymentHeaders.id),
            eq(paymentHeaders.organisationId, tenantId),
          ),
        )
        .orderBy(desc(journalEntries.createdOn))
        .limit(200);

      // Attach CoA names
      const allCodes = [...new Set(rows.flatMap(r => [r.debitCoa, r.creditCoa]))];
      const coaRows = allCodes.length
        ? await db.select({ code: chartOfAccounts.code, name: chartOfAccounts.name })
            .from(chartOfAccounts)
            .where(and(
              eq(chartOfAccounts.organisationId, tenantId),
              inArray(chartOfAccounts.code, allCodes),
            ))
        : [];
      const coaMap = Object.fromEntries(coaRows.map(c => [c.code, c.name]));

      return res.json({
        data: rows.map(r => ({
          ...r,
          debitCoaName:  coaMap[r.debitCoa]  ?? r.debitCoa,
          creditCoaName: coaMap[r.creditCoa] ?? r.creditCoa,
        })),
      });
    } catch (err) {
      console.error("[GET /api/accounting/journal-entries]", err);
      return res.status(500).json({ error: "Internal server error" });
    }
  }
);

// ─── GET /api/accounting/payments ───────────────────────────────────────────
router.get(
  "/accounting/payments",
  authenticate,
  requireRole(...STAFF_ROLES),
  async (req, res) => {
    try {
      const tenantId = requireTenant(req, res);
      if (!tenantId) return;
      const { paymentType, status, date_from, date_to } = req.query as Record<string, string>;
      const conds: SQL[] = [eq(paymentHeaders.organisationId, tenantId)];
      if (paymentType) conds.push(eq(paymentHeaders.paymentType, paymentType));
      if (status)      conds.push(eq(paymentHeaders.status, status));
      if (date_from)   conds.push(gte(paymentHeaders.paymentDate, date_from));
      if (date_to)     conds.push(lte(paymentHeaders.paymentDate, date_to));
      const where = and(...conds);

      const rows = await db
        .select()
        .from(paymentHeaders)
        .where(where)
        .orderBy(desc(paymentHeaders.createdOn))
        .limit(200);

      return res.json({ data: rows });
    } catch (err) {
      console.error("[GET /api/accounting/payments]", err);
      return res.status(500).json({ error: "Internal server error" });
    }
  }
);

// ─── GET /api/accounting/payments/:id ───────────────────────────────────────
router.get(
  "/accounting/payments/:id",
  authenticate,
  requireRole(...STAFF_ROLES),
  async (req, res) => {
    try {
      const tenantId = requireTenant(req, res);
      if (!tenantId) return;
      const [header] = await db
        .select()
        .from(paymentHeaders)
        .where(and(
          eq(paymentHeaders.id, req.params.id as string),
          eq(paymentHeaders.organisationId, tenantId),
        ));
      if (!header) return res.status(404).json({ error: "Payment not found" });

      const lines = await db
        .select()
        .from(paymentLines)
        .where(and(
          eq(paymentLines.paymentHeaderId, req.params.id as string),
          eq(paymentLines.organisationId, tenantId),
        ));

      const entries = await db
        .select()
        .from(journalEntries)
        .where(eq(journalEntries.paymentHeaderId, req.params.id as string));

      return res.json({ ...header, lines, journalEntries: entries });
    } catch (err) {
      console.error("[GET /api/accounting/payments/:id]", err);
      return res.status(500).json({ error: "Internal server error" });
    }
  }
);

// ─── POST /api/accounting/payments ──────────────────────────────────────────
router.post(
  "/accounting/payments",
  authenticate,
  requireRole(...STAFF_ROLES),
  async (req, res) => {
    try {
      const tenantId = requireTenant(req, res);
      if (!tenantId) return;
      const {
        contractId,
        invoiceId,
        paymentDate, paymentMethod, paymentType,
        bankReference, notes,
        receivedFromName, paidToName,
        receivedFromId, paidToId,
        lines: lineItems = [],
      } = req.body;

      // camp_coordinator: check delegated finance permission
      const user = req.user!;
      if (user.role === "camp_coordinator" && user.organisationId && contractId) {
        const pgId = await resolvePackageGroupIdFromContractId(contractId as string);
        if (pgId) {
          const ok = await assertFinanceDelegation(res, user.organisationId, user.id, pgId, "edit", req.ip);
          if (!ok) return;
        }
      }

      if (!paymentDate || !paymentType) {
        return res.status(400).json({ error: "paymentDate and paymentType are required" });
      }

      if (!Array.isArray(lineItems) || lineItems.length === 0) {
        return res.status(400).json({ error: "At least one payment line is required" });
      }

      // Total from lines (server-side calculation)
      const totalAmount = (lineItems as any[]).reduce(
        (sum: number, l: any) => sum + Number(l.amount ?? 0), 0
      );

      // Store receivedFromName/paidToName in notes JSON
      const notesPayload = JSON.stringify({
        receivedFromName: receivedFromName ?? null,
        paidToName: paidToName ?? null,
        notes: notes ?? null,
      });

      const result = await db.transaction(async (tx) => {
        // 1. Create payment header
        const [header] = await tx.insert(paymentHeaders).values({
          paymentRef:    genPayRef(),
          contractId:    contractId ?? null,
          invoiceId:     invoiceId && invoiceId.trim() ? invoiceId : null,
          paymentDate,
          totalAmount:   String(totalAmount.toFixed(2)),
          currency:      "AUD",
          paymentMethod: paymentMethod ?? null,
          paymentType,
          receivedFrom:  receivedFromId ?? null,
          paidTo:        paidToId ?? null,
          bankReference: bankReference ?? null,
          notes:         notesPayload,
          createdBy:     userId(req),
          status:        "Active",
          organisationId: tenantId,
        }).returning();

        // 2. Insert payment lines
        const lineVals = (lineItems as any[]).map((l: any) => ({
          paymentHeaderId:   header.id,
          contractProductId: l.contractProductId ?? null,
          invoiceId:         l.invoiceId ?? null,
          coaCode:           l.coaCode ?? null,
          splitType:         l.splitType ?? null,
          staffId:           l.staffId ?? null,
          amount:            String(Number(l.amount ?? 0).toFixed(2)),
          description:       l.description ?? null,
          organisationId:    tenantId,
        }));
        const insertedLines = await tx.insert(paymentLines).values(lineVals).returning();

        // 3. Update AR/AP status on linked contract_products
        const cpIds = (lineItems as any[])
          .map((l: any) => l.contractProductId)
          .filter(Boolean);

        if (cpIds.length > 0) {
          if (paymentType === "trust_receipt") {
            await tx
              .update(contractProducts)
              .set({ arStatus: "paid" })
              .where(inArray(contractProducts.id, cpIds));

            // ap_trigger='on_ar_paid': flip pending AP to 'ready' so finance can remit.
            await tx
              .update(contractProducts)
              .set({ apStatus: "ready" })
              .where(and(
                inArray(contractProducts.id, cpIds),
                eq(contractProducts.apTrigger, "on_ar_paid"),
                eq(contractProducts.apStatus, "pending"),
              ));
          } else if (paymentType === "trust_transfer") {
            await tx
              .update(contractProducts)
              .set({ apStatus: "paid" })
              .where(inArray(contractProducts.id, cpIds));
          }
        }

        // 4. Auto-generate journal entries (one per line, via centralized service).
        //    DR/CR mapping uses paymentType + splitType (see journalEntryService.ts).
        for (const line of insertedLines) {
          await createJournalEntriesForPaymentLine(
            {
              id:                line.id,
              paymentHeaderId:   header.id,
              invoiceId:         line.invoiceId ?? null,
              contractProductId: line.contractProductId ?? null,
              splitType:         line.splitType ?? null,
              amount:            line.amount as unknown as string,
              staffId:           line.staffId ?? null,
              description:       line.description ?? null,
              createdOn:         (line.createdOn as Date) ?? new Date(),
            },
            {
              id:             header.id,
              organisationId: header.organisationId ?? tenantId,
              paymentRef:     header.paymentRef ?? null,
              paymentDate:    header.paymentDate as unknown as string,
              paymentType:    header.paymentType,
              receivedFrom:   header.receivedFrom ?? null,
              paidTo:         header.paidTo ?? null,
            },
            userId(req),
            tx as any,
          );
        }

        const journalRows = await tx
          .select()
          .from(journalEntries)
          .where(eq(journalEntries.paymentHeaderId, header.id));

        return { header, lines: insertedLines, journalEntries: journalRows };
      });

      // === BRIDGE: auto-create transaction record ===
      try {
        // trust_receipt (customer deposit) → transactionType: 'payment_received', set creditAmount
        // trust_transfer (remittance)      → transactionType: 'bank_transfer',    set amount
        // other types                      → transactionType: paymentType,        set amount
        const txType =
          paymentType === "trust_receipt"  ? "payment_received" :
          paymentType === "trust_transfer" ? "bank_transfer"    :
          paymentType;

        const firstLine = (lineItems as any[])[0];

        await db.insert(transactions).values({
          transactionType:  txType,
          transactionDate:  paymentDate,
          amount:           String(totalAmount.toFixed(2)),
          creditAmount:     paymentType === "trust_receipt"
                              ? String(totalAmount.toFixed(2))
                              : null,
          currency:         "AUD",
          description:      `${paymentType} — ${result.header.paymentRef} — ${totalAmount.toFixed(2)}`,
          bankReference:    bankReference ?? null,
          accountId:        receivedFromId ?? paidToId ?? null,
          paymentInfoId:    result.header.id,
          contractId:       firstLine?.contractId ?? null,
          invoiceId:        firstLine?.invoiceId  ?? null,
          createdBy:        userId(req),
          status:           "Active",
          organisationId:   tenantId,
        });
      } catch (bridgeError) {
        // Bridge failure does not affect the payment_header save — treat as success
        console.error("[Bridge] Failed to create transaction record:", bridgeError);
      }
      // === END BRIDGE ===

      // ── Tax Invoice auto-generation (post-transaction, non-blocking) ──────
      if (paymentType === "trust_transfer") {
        const cpIds = (lineItems as any[])
          .map((l: any) => l.contractProductId)
          .filter(Boolean) as string[];

        if (cpIds.length > 0) {
          const cpRows = await db
            .select({ id: contractProducts.id, remittanceMethod: contractProducts.remittanceMethod })
            .from(contractProducts)
            .where(inArray(contractProducts.id, cpIds));

          for (const cp of cpRows) {
            if (!cp.remittanceMethod) continue;
            generateTaxInvoice(cp.id, result.header.id, userId(req)).catch((err) => {
              console.error(`[TaxInvoice] Generation failed for CP ${cp.id}:`, String(err));
            });
          }
        }
      }

      return res.status(201).json(result);
    } catch (err) {
      console.error("[POST /api/accounting/payments]", err);
      return res.status(500).json({ error: "Internal server error" });
    }
  }
);

// ─── PATCH /api/accounting/payments/:id/void ────────────────────────────────
router.patch(
  "/accounting/payments/:id/void",
  authenticate,
  requireRole(...ADMIN_ROLES),
  async (req, res) => {
    try {
      const tenantId = requireTenant(req, res);
      if (!tenantId) return;
      const [existing] = await db
        .select({ id: paymentHeaders.id, status: paymentHeaders.status })
        .from(paymentHeaders)
        .where(and(
          eq(paymentHeaders.id, req.params.id as string),
          eq(paymentHeaders.organisationId, tenantId),
        ));

      if (!existing) return res.status(404).json({ error: "Payment not found" });
      if (existing.status === "Void") return res.status(400).json({ error: "Payment already voided" });

      const [updated] = await db
        .update(paymentHeaders)
        .set({ status: "Void", modifiedOn: new Date() })
        .where(and(
          eq(paymentHeaders.id, req.params.id as string),
          eq(paymentHeaders.organisationId, tenantId),
        ))
        .returning();

      // Cascade: also deactivate any linked transaction records
      try {
        await db
          .update(transactions)
          .set({ status: "Inactive" })
          .where(and(
            eq(transactions.paymentInfoId, req.params.id as string),
            eq(transactions.organisationId, tenantId),
            eq(transactions.status, "Active"),
          ));
      } catch (cascadeErr) {
        console.error("[PATCH /payments/:id/void] cascade transaction deactivation failed:", cascadeErr);
      }

      return res.json(updated);
    } catch (err) {
      console.error("[PATCH /api/accounting/payments/:id/void]", err);
      return res.status(500).json({ error: "Internal server error" });
    }
  }
);

// ─── LOOKUP: accounts search ─────────────────────────────────────────────────
router.get("/accounting/payments-lookup/accounts", authenticate, async (req, res) => {
  try {
    const tenantId = requireTenant(req, res);
    if (!tenantId) return;
    const { search = "" } = req.query as Record<string, string>;
    const conds: SQL[] = [eq(accounts.organisationId, tenantId)];
    if (search) conds.push(ilike(accounts.name, `%${search}%`));
    const rows = await db
      .select({ id: accounts.id, name: accounts.name, accountType: accounts.accountType })
      .from(accounts)
      .where(and(...conds))
      .orderBy(asc(accounts.name))
      .limit(20);
    return res.json(rows);
  } catch (err) {
    console.error("[GET /accounting/payments-lookup/accounts]", err);
    return res.status(500).json({ error: "Internal server error" });
  }
});

// ─── LOOKUP: contract search ──────────────────────────────────────────────────
router.get("/accounting/payments-lookup/contracts", authenticate, async (req, res) => {
  try {
    const tenantId = requireTenant(req, res);
    if (!tenantId) return;
    const { search = "" } = req.query as Record<string, string>;
    const r = (x: any) => x.rows ?? (x as any[]);
    const rows = await db.execute(sql`
      SELECT c.id, c.contract_number, c.student_name, c.status,
             a.id   AS account_id,
             a.name AS account_name
      FROM contracts c
      LEFT JOIN accounts a ON a.id = c.account_id
      WHERE c.status IN ('active', 'signed')
        AND c.organisation_id = ${tenantId}::uuid
        AND (
          ${search} = ''
          OR c.contract_number ILIKE ${'%' + search + '%'}
          OR c.student_name    ILIKE ${'%' + search + '%'}
          OR a.name            ILIKE ${'%' + search + '%'}
        )
      ORDER BY c.created_at DESC
      LIMIT 20
    `);
    return res.json(r(rows));
  } catch (err) {
    console.error("[GET /accounting/payments-lookup/contracts]", err);
    return res.status(500).json({ error: "Internal server error" });
  }
});

// ─── LOOKUP: contract products ────────────────────────────────────────────────
router.get("/accounting/payments-lookup/contracts/:id/products", authenticate, async (req, res) => {
  try {
    const tenantId = requireTenant(req, res);
    if (!tenantId) return;
    const r = (x: any) => x.rows ?? (x as any[]);
    const rows = await db.execute(sql`
      SELECT id,
             COALESCE(name, product_name) AS name,
             ar_amount, ar_status,
             ap_amount, ap_status,
             service_module_type
      FROM contract_products
      WHERE contract_id = ${req.params.id as string}::uuid
        AND organisation_id = ${tenantId}::uuid
      ORDER BY COALESCE(sort_index, 0), created_at
    `);
    return res.json(r(rows));
  } catch (err) {
    console.error("[GET /accounting/payments-lookup/contracts/:id/products]", err);
    return res.status(500).json({ error: "Internal server error" });
  }
});

// ─── PAYMENTS BY CONTRACT ─────────────────────────────────────────────────────
router.get("/accounting/payments/by-contract/:contractId", authenticate, async (req, res) => {
  try {
    const tenantId = requireTenant(req, res);
    if (!tenantId) return;
    const { contractId } = req.params as Record<string, string>;
    const r = (x: any) => x.rows ?? (x as any[]);
    const rows = await db.execute(sql`
      SELECT
        ph.id,
        ph.payment_ref,
        ph.payment_date,
        ph.total_amount,
        ph.payment_type,
        ph.payment_method,
        ph.bank_reference,
        ph.status,
        ph.notes,
        ph.received_from,
        ph.paid_to,
        rf.name  AS received_from_name,
        pt.name  AS paid_to_name,
        pl.id    AS line_id,
        pl.amount          AS line_amount,
        pl.split_type,
        pl.description     AS line_description,
        cp.name AS product_name,
        cp.ar_status,
        cp.ap_status
      FROM payment_lines pl
      JOIN payment_headers ph ON ph.id = pl.payment_header_id
      JOIN contract_products cp ON cp.id = pl.contract_product_id
      LEFT JOIN accounts rf ON rf.id = ph.received_from
      LEFT JOIN accounts pt ON pt.id = ph.paid_to
      WHERE cp.contract_id = ${contractId}::uuid
        AND ph.organisation_id = ${tenantId}::uuid
        AND cp.organisation_id = ${tenantId}::uuid
        AND ph.status != 'Void'
      ORDER BY ph.payment_date DESC, ph.created_on DESC
    `);
    return res.json(r(rows));
  } catch (err) {
    console.error("[GET /api/accounting/payments/by-contract]", err);
    return res.status(500).json({ error: "Internal server error" });
  }
});

// ─── LEDGER BY ACCOUNT ────────────────────────────────────────────────────────
router.get("/accounting/ledger/by-account/:accountId", authenticate, async (req, res) => {
  try {
    const tenantId = requireTenant(req, res);
    if (!tenantId) return;
    const { accountId } = req.params as Record<string, string>;
    const r = (x: any) => x.rows ?? (x as any[]);
    const rows = await db.execute(sql`
      SELECT
        'payment' AS source,
        ph.id,
        ph.payment_ref      AS ref,
        ph.payment_date     AS entry_date,
        ph.total_amount     AS amount,
        ph.payment_type     AS type,
        ph.payment_method   AS method,
        ph.status,
        ph.bank_reference,
        ph.notes,
        CASE
          WHEN ph.received_from = ${accountId}::uuid THEN 'received'
          ELSE 'paid'
        END AS direction,
        rf.name AS received_from_name,
        pt.name AS paid_to_name
      FROM payment_headers ph
      LEFT JOIN accounts rf ON rf.id = ph.received_from
      LEFT JOIN accounts pt ON pt.id = ph.paid_to
      WHERE (ph.received_from = ${accountId}::uuid OR ph.paid_to = ${accountId}::uuid)
        AND ph.organisation_id = ${tenantId}::uuid
        AND ph.status != 'Void'

      UNION ALL

      SELECT
        'transaction' AS source,
        t.id,
        COALESCE(t.bank_reference, t.id::text) AS ref,
        t.transaction_date  AS entry_date,
        COALESCE(t.credit_amount, t.amount)    AS amount,
        t.transaction_type  AS type,
        NULL                AS method,
        t.status,
        t.bank_reference,
        t.description       AS notes,
        'transaction'       AS direction,
        NULL                AS received_from_name,
        NULL                AS paid_to_name
      FROM transactions t
      WHERE t.account_id = ${accountId}::uuid
        AND t.organisation_id = ${tenantId}::uuid

      ORDER BY entry_date DESC NULLS LAST
      LIMIT 200
    `);
    return res.json(r(rows));
  } catch (err) {
    console.error("[GET /api/accounting/ledger/by-account]", err);
    return res.status(500).json({ error: "Internal server error" });
  }
});

export default router;
