import { Router } from "express";
import { db } from "@workspace/db";
import {
  paymentHeaders, paymentLines, journalEntries,
  chartOfAccounts, contractProducts, contracts,
} from "@workspace/db/schema";
import { eq, and, gte, lte, inArray, asc, desc, SQL } from "drizzle-orm";
import { generateTaxInvoice } from "../services/taxInvoiceService.js";
import { authenticate } from "../middleware/authenticate.js";
import { requireRole } from "../middleware/requireRole.js";

const router = Router();
const STAFF_ROLES  = ["super_admin", "admin", "camp_coordinator"];
const ADMIN_ROLES  = ["super_admin", "admin"];

// ─── JE mapping ─────────────────────────────────────────────────────────────
const JE_MAP: Record<string, { debit: string; credit: string }> = {
  trust_receipt:  { debit: "1200", credit: "1300" },
  trust_transfer: { debit: "2100", credit: "1200" },
  commission:     { debit: "1100", credit: "3100" },
  direct:         { debit: "4700", credit: "1100" },
};

function genPayRef(): string {
  return "PAY-" + Date.now().toString(36).toUpperCase().padStart(8, "0");
}

function userId(req: any): string {
  return req.user?.id ?? "00000000-0000-0000-0000-000000000000";
}

// ─── GET /api/accounting/journal-entries ────────────────────────────────────
router.get(
  "/accounting/journal-entries",
  authenticate,
  requireRole(...STAFF_ROLES),
  async (req, res) => {
    try {
      const rows = await db
        .select({
          id:              journalEntries.id,
          entryDate:       journalEntries.entryDate,
          paymentHeaderId: journalEntries.paymentHeaderId,
          debitCoa:        journalEntries.debitCoa,
          creditCoa:       journalEntries.creditCoa,
          amount:          journalEntries.amount,
          entryType:       journalEntries.entryType,
          contractId:      journalEntries.contractId,
          autoGenerated:   journalEntries.autoGenerated,
          createdOn:       journalEntries.createdOn,
          paymentRef:      paymentHeaders.paymentRef,
          paymentStatus:   paymentHeaders.status,
        })
        .from(journalEntries)
        .leftJoin(paymentHeaders, eq(journalEntries.paymentHeaderId, paymentHeaders.id))
        .orderBy(desc(journalEntries.createdOn))
        .limit(200);

      // Attach CoA names
      const allCodes = [...new Set(rows.flatMap(r => [r.debitCoa, r.creditCoa]))];
      const coaRows = allCodes.length
        ? await db.select({ code: chartOfAccounts.code, name: chartOfAccounts.name })
            .from(chartOfAccounts)
            .where(inArray(chartOfAccounts.code, allCodes))
        : [];
      const coaMap = Object.fromEntries(coaRows.map(c => [c.code, c.name]));

      return res.json({
        data: rows.map(r => ({
          ...r,
          debitCoaName:  coaMap[r.debitCoa]  ?? r.debitCoa,
          creditCoaName: coaMap[r.creditCoa] ?? r.creditCoa,
        })),
      });
    } catch (err) {
      console.error("[GET /api/accounting/journal-entries]", err);
      return res.status(500).json({ error: "Internal server error" });
    }
  }
);

// ─── GET /api/accounting/payments ───────────────────────────────────────────
router.get(
  "/accounting/payments",
  authenticate,
  requireRole(...STAFF_ROLES),
  async (req, res) => {
    try {
      const { paymentType, status, date_from, date_to } = req.query as Record<string, string>;
      const conds: SQL[] = [];
      if (paymentType) conds.push(eq(paymentHeaders.paymentType, paymentType));
      if (status)      conds.push(eq(paymentHeaders.status, status));
      if (date_from)   conds.push(gte(paymentHeaders.paymentDate, date_from));
      if (date_to)     conds.push(lte(paymentHeaders.paymentDate, date_to));
      const where = conds.length ? and(...conds) : undefined;

      const rows = await db
        .select()
        .from(paymentHeaders)
        .where(where)
        .orderBy(desc(paymentHeaders.createdOn))
        .limit(200);

      return res.json({ data: rows });
    } catch (err) {
      console.error("[GET /api/accounting/payments]", err);
      return res.status(500).json({ error: "Internal server error" });
    }
  }
);

// ─── GET /api/accounting/payments/:id ───────────────────────────────────────
router.get(
  "/accounting/payments/:id",
  authenticate,
  requireRole(...STAFF_ROLES),
  async (req, res) => {
    try {
      const [header] = await db
        .select()
        .from(paymentHeaders)
        .where(eq(paymentHeaders.id, req.params.id));
      if (!header) return res.status(404).json({ error: "Payment not found" });

      const lines = await db
        .select()
        .from(paymentLines)
        .where(eq(paymentLines.paymentHeaderId, req.params.id));

      const entries = await db
        .select()
        .from(journalEntries)
        .where(eq(journalEntries.paymentHeaderId, req.params.id));

      return res.json({ ...header, lines, journalEntries: entries });
    } catch (err) {
      console.error("[GET /api/accounting/payments/:id]", err);
      return res.status(500).json({ error: "Internal server error" });
    }
  }
);

// ─── POST /api/accounting/payments ──────────────────────────────────────────
router.post(
  "/accounting/payments",
  authenticate,
  requireRole(...STAFF_ROLES),
  async (req, res) => {
    try {
      const {
        paymentDate, paymentMethod, paymentType,
        bankReference, notes,
        receivedFromName, paidToName,
        receivedFromId, paidToId,
        lines: lineItems = [],
      } = req.body;

      if (!paymentDate || !paymentType) {
        return res.status(400).json({ error: "paymentDate and paymentType are required" });
      }

      const jeMap = JE_MAP[paymentType];
      if (!jeMap) {
        return res.status(400).json({ error: `Unknown paymentType: ${paymentType}` });
      }

      // Total from lines (server-side calculation)
      const totalAmount = (lineItems as any[]).reduce(
        (sum: number, l: any) => sum + Number(l.amount ?? 0), 0
      );

      // Store receivedFromName/paidToName in notes JSON
      const notesPayload = JSON.stringify({
        receivedFromName: receivedFromName ?? null,
        paidToName: paidToName ?? null,
        notes: notes ?? null,
      });

      const result = await db.transaction(async (tx) => {
        // 1. Create payment header
        const [header] = await tx.insert(paymentHeaders).values({
          paymentRef:    genPayRef(),
          paymentDate,
          totalAmount:   String(totalAmount.toFixed(2)),
          currency:      "AUD",
          paymentMethod: paymentMethod ?? null,
          paymentType,
          receivedFrom:  receivedFromId ?? null,
          paidTo:        paidToId ?? null,
          bankReference: bankReference ?? null,
          notes:         notesPayload,
          createdBy:     userId(req),
          status:        "Active",
        }).returning();

        // 2. Insert payment lines
        const insertedLines: any[] = [];
        if (Array.isArray(lineItems) && lineItems.length > 0) {
          const vals = lineItems.map((l: any) => ({
            paymentHeaderId:   header.id,
            contractProductId: l.contractProductId ?? null,
            coaCode:           l.coaCode ?? null,
            splitType:         l.splitType ?? null,
            amount:            String(Number(l.amount ?? 0).toFixed(2)),
            description:       l.description ?? null,
          }));
          const lines = await tx.insert(paymentLines).values(vals).returning();
          insertedLines.push(...lines);
        }

        // 3. Update AR/AP status on linked contract_products
        const cpIds = (lineItems as any[])
          .map((l: any) => l.contractProductId)
          .filter(Boolean);

        if (cpIds.length > 0) {
          if (paymentType === "trust_receipt") {
            await tx
              .update(contractProducts)
              .set({ arStatus: "paid" })
              .where(inArray(contractProducts.id, cpIds));
          } else if (paymentType === "trust_transfer") {
            await tx
              .update(contractProducts)
              .set({ apStatus: "paid" })
              .where(inArray(contractProducts.id, cpIds));
          }
        }

        // 4. Auto-generate journal entry
        const [je] = await tx.insert(journalEntries).values({
          entryDate:       paymentDate,
          paymentHeaderId: header.id,
          debitCoa:        jeMap.debit,
          creditCoa:       jeMap.credit,
          amount:          String(totalAmount.toFixed(2)),
          description:     `Auto-generated JE for ${paymentType} — ${header.paymentRef}`,
          entryType:       paymentType,
          autoGenerated:   true,
          createdBy:       userId(req),
        }).returning();

        return { header, lines: insertedLines, journalEntry: je };
      });

      // ── Tax Invoice auto-generation (post-transaction, non-blocking) ──────
      if (paymentType === "trust_transfer") {
        const cpIds = (lineItems as any[])
          .map((l: any) => l.contractProductId)
          .filter(Boolean) as string[];

        if (cpIds.length > 0) {
          const cpRows = await db
            .select({ id: contractProducts.id, remittanceMethod: contractProducts.remittanceMethod })
            .from(contractProducts)
            .where(inArray(contractProducts.id, cpIds));

          for (const cp of cpRows) {
            if (!cp.remittanceMethod) continue;
            generateTaxInvoice(cp.id, result.header.id, userId(req)).catch((err) => {
              console.error(`[TaxInvoice] Generation failed for CP ${cp.id}:`, String(err));
            });
          }
        }
      }

      return res.status(201).json(result);
    } catch (err) {
      console.error("[POST /api/accounting/payments]", err);
      return res.status(500).json({ error: "Internal server error" });
    }
  }
);

// ─── PATCH /api/accounting/payments/:id/void ────────────────────────────────
router.patch(
  "/accounting/payments/:id/void",
  authenticate,
  requireRole(...ADMIN_ROLES),
  async (req, res) => {
    try {
      const [existing] = await db
        .select({ id: paymentHeaders.id, status: paymentHeaders.status })
        .from(paymentHeaders)
        .where(eq(paymentHeaders.id, req.params.id));

      if (!existing) return res.status(404).json({ error: "Payment not found" });
      if (existing.status === "Void") return res.status(400).json({ error: "Payment already voided" });

      const [updated] = await db
        .update(paymentHeaders)
        .set({ status: "Void", modifiedOn: new Date() })
        .where(eq(paymentHeaders.id, req.params.id))
        .returning();

      return res.json(updated);
    } catch (err) {
      console.error("[PATCH /api/accounting/payments/:id/void]", err);
      return res.status(500).json({ error: "Internal server error" });
    }
  }
);

export default router;
