import { Router } from "express";
import { db } from "@workspace/db";
import { contractFinanceItems, userLedger, receipts } from "@workspace/db/schema";
import { eq, and, desc } from "drizzle-orm";
import { authenticate } from "../middleware/authenticate.js";
import { requireRole } from "../middleware/requireRole.js";
import {
  financeAutoGenerate,
  buildFinanceSummary,
  confirmPayment,
} from "../services/contractFinanceService.js";
import { generateReceiptPdf } from "../services/receiptPdfService.js";

const router = Router();

// ── Role helpers ──────────────────────────────────────────────────────────
const FULL_ACCESS   = ["super_admin", "admin"];
const EDIT_ACCESS   = [...FULL_ACCESS, "camp_coordinator"];

function canViewContract(user: any, contract: { campProviderId?: string | null }): boolean {
  if (FULL_ACCESS.includes(user.role)) return true;
  if (user.role === "camp_coordinator") return contract.campProviderId === user.id;
  if (user.role === "education_agent") return true; // own contracts via finance item later
  return false;
}

// ── POST /contracts/:id/finance/generate ─────────────────────────────────
router.post(
  "/contracts/:id/finance/generate",
  authenticate,
  requireRole(...EDIT_ACCESS),
  async (req, res) => {
    try {
      const result = await financeAutoGenerate(req.params.id);
      return res.json(result);
    } catch (err: any) {
      console.error("finance/generate error:", err.message);
      return res.status(500).json({ error: err.message ?? "Internal Server Error" });
    }
  }
);

// ── GET /contracts/:id/finance ────────────────────────────────────────────
router.get("/contracts/:id/finance", authenticate, async (req, res) => {
  try {
    const user = req.user!;
    // Role: EA and Client only see their items; others see all
    const data = await buildFinanceSummary(req.params.id);

    // Education agents: only show their own items
    if (user.role === "education_agent") {
      data.receivable = data.receivable.filter(
        i => i.linkedAgentId === user.id || i.itemCategory === "agent_invoice"
      );
      data.payable = data.payable.filter(i => i.linkedAgentId === user.id);
    }

    return res.json(data);
  } catch (err: any) {
    console.error("GET finance error:", err.message);
    return res.status(500).json({ error: "Internal Server Error" });
  }
});

// ── POST /contracts/:id/finance/items ─────────────────────────────────────
router.post(
  "/contracts/:id/finance/items",
  authenticate,
  requireRole(...EDIT_ACCESS),
  async (req, res) => {
    try {
      const [item] = await db
        .insert(contractFinanceItems)
        .values({
          ...req.body,
          contractId: req.params.id,
          isAutoGenerated: false,
          isDeleted: false,
        })
        .returning();
      return res.status(201).json(item);
    } catch (err: any) {
      console.error("POST finance/items error:", err.message);
      return res.status(500).json({ error: "Internal Server Error" });
    }
  }
);

// ── PUT /finance/items/:itemId ─────────────────────────────────────────────
router.put(
  "/finance/items/:itemId",
  authenticate,
  requireRole(...EDIT_ACCESS),
  async (req, res) => {
    try {
      const ALLOWED_FIELDS = [
        "label", "estimatedAmount", "actualAmount", "dueDate",
        "notes", "linkedPartnerId", "linkedAgentId",
        "commissionType", "commissionRate", "commissionFixed",
        "status", "currency", "costCenter",
      ];
      const updates: Record<string, unknown> = { updatedAt: new Date() };
      for (const key of ALLOWED_FIELDS) {
        if (key in req.body) updates[key] = req.body[key] ?? null;
      }

      const [updated] = await db
        .update(contractFinanceItems)
        .set(updates)
        .where(and(eq(contractFinanceItems.id, req.params.itemId), eq(contractFinanceItems.isDeleted, false)))
        .returning();

      if (!updated) return res.status(404).json({ error: "Finance item not found" });
      return res.json(updated);
    } catch (err: any) {
      console.error("PUT finance/items error:", err.message);
      return res.status(500).json({ error: "Internal Server Error" });
    }
  }
);

// ── DELETE /finance/items/:itemId (soft delete) ────────────────────────────
router.delete(
  "/finance/items/:itemId",
  authenticate,
  requireRole(...FULL_ACCESS),
  async (req, res) => {
    try {
      const [updated] = await db
        .update(contractFinanceItems)
        .set({ isDeleted: true, updatedAt: new Date() })
        .where(eq(contractFinanceItems.id, req.params.itemId))
        .returning();
      if (!updated) return res.status(404).json({ error: "Finance item not found" });
      return res.json({ success: true, id: updated.id });
    } catch (err: any) {
      console.error("DELETE finance/items error:", err.message);
      return res.status(500).json({ error: "Internal Server Error" });
    }
  }
);

// ── POST /finance/items/:itemId/confirm-payment ────────────────────────────
router.post(
  "/finance/items/:itemId/confirm-payment",
  authenticate,
  requireRole(...EDIT_ACCESS),
  async (req, res) => {
    try {
      const { actualAmount, paidDate, referenceNo, paymentMethod, notes } = req.body;
      if (!actualAmount || !paidDate) {
        return res.status(400).json({ error: "actualAmount and paidDate are required" });
      }
      const result = await confirmPayment(
        req.params.itemId,
        { actualAmount: parseFloat(actualAmount), paidDate, referenceNo, paymentMethod, notes },
        req.user!.id,
      );
      return res.json(result);
    } catch (err: any) {
      console.error("confirm-payment error:", err.message);
      return res.status(err.message === "Finance item not found" ? 404 : 500)
        .json({ error: err.message ?? "Internal Server Error" });
    }
  }
);

// ── GET /contracts/:id/finance/ledger ─────────────────────────────────────
router.get(
  "/contracts/:id/finance/ledger",
  authenticate,
  requireRole(...FULL_ACCESS, "camp_coordinator"),
  async (req, res) => {
    try {
      const entries = await db
        .select()
        .from(userLedger)
        .where(eq(userLedger.contractId, req.params.id))
        .orderBy(desc(userLedger.transactionDate), desc(userLedger.createdAt));
      return res.json({ data: entries });
    } catch (err: any) {
      console.error("GET finance/ledger error:", err.message);
      return res.status(500).json({ error: "Internal Server Error" });
    }
  }
);

// ── GET /finance/receipts/:receiptId/pdf ──────────────────────────────────
router.get(
  "/finance/receipts/:receiptId/pdf",
  authenticate,
  async (req, res) => {
    try {
      const { receiptId } = req.params;
      // Verify receipt exists
      const [rcpt] = await db.select({ id: receipts.id, receiptNumber: receipts.receiptNumber })
        .from(receipts).where(eq(receipts.id, receiptId)).limit(1);
      if (!rcpt) return res.status(404).json({ error: "Receipt not found" });

      const pdfBuffer = await generateReceiptPdf(receiptId);
      const filename = `${rcpt.receiptNumber ?? "receipt"}.pdf`;
      res.set({
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Content-Length": String(pdfBuffer.length),
      });
      return res.send(pdfBuffer);
    } catch (err: any) {
      console.error("receipt-pdf error:", err.message);
      return res.status(500).json({ error: err.message ?? "Failed to generate PDF" });
    }
  }
);

// ── GET /contracts/:id/finance/receipts ───────────────────────────────────
// Returns receipts linked to finance items for this contract
router.get(
  "/contracts/:id/finance/receipts",
  authenticate,
  requireRole(...FULL_ACCESS, "camp_coordinator"),
  async (req, res) => {
    try {
      const { contractFinanceItems: cfi } = await import("@workspace/db/schema");
      const items = await db.select({ id: cfi.id }).from(cfi)
        .where(and(eq(cfi.contractId, req.params.id), eq(cfi.isDeleted, false)));
      const itemIds = items.map(i => i.id);
      if (itemIds.length === 0) return res.json({ data: [] });

      const { inArray } = await import("drizzle-orm");
      const rcpts = await db.select().from(receipts)
        .where(inArray(receipts.financeItemId!, itemIds))
        .orderBy(desc(receipts.receiptDate));
      return res.json({ data: rcpts });
    } catch (err: any) {
      console.error("GET finance/receipts error:", err.message);
      return res.status(500).json({ error: "Internal Server Error" });
    }
  }
);

export default router;
