import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import storageRouter from "./storage.js";
import authRouter from "./auth.js";
import usersRouter from "./users.js";
import packagesRouter from "./packages.js";
import applicationsRouter from "./applications.js";
import contractsRouter from "./contracts.js";
import financeRouter from "./finance.js";
import dashboardRouter from "./dashboard.js";
import publicRouter from "./public.js";
import servicesRouter from "./services.js";
import myAccountingRouter from "./my-accounting.js";
import reportsRouter from "./reports.js";
import notificationsRouter from "./notifications.js";
import tasksRouter from "./tasks.js";
import notesRouter from "./notes.js";
import dataManagerRouter from "./data-manager.js";
import ledgerRouter from "./ledger.js";
import documentsRouter from "./documents.js";
import settingsRouter from "./settings.js";
import settingsLookupsRouter from "./settings-lookups.js";
import chatbotRouter from "./chatbot.js";
import aiRouter from "./ai.js";
import contractFinanceRouter from "./contract-finance.js";
import contractSigningRouter from "./contract-signing.js";
import crmContactsRouter from "./crm-contacts.js";
import crmLeadsRouter from "./crm-leads.js";
import crmQuotesRouter from "./crm-quotes.js";
import accountingCoaRouter from "./accounting-coa.js";
import accountingArApRouter from "./accounting-arap.js";
import accountingPaymentsRouter from "./accounting-payments.js";
import servicesStudyAbroadRouter from "./services-study-abroad.js";
import servicesAccommodationRouter from "./services-accommodation.js";
import servicesPickupRouter from "./services-pickup.js";
import servicesInternshipRouter from "./services-internship.js";
import servicesGuardianRouter from "./services-guardian.js";
import servicesOtherRouter from "./services-other.js";
import servicesVisaRouter from "./services-visa.js";
import servicesTourRouter from "./services-tour.js";
import campApplicationsRouter from "./camp-applications.js";
import campServicesRouter from "./camp-services.js";
import campPhotosRouter from "./camp-photos.js";
import dashboardCrmRouter from "./dashboard-crm.js";
import dashboardV2Router from "./dashboard-v2.js";
import crmAccountsRouter from "./crm-accounts.js";
import productCatalogRouter from "./product-catalog.js";
import accountingTransactionsRouter from "./accounting-transactions.js";
import quoteProductsRouter from "./quote-products.js";
import crmContractsRouter from "./crm-contracts.js";
import paymentHeadersRouter from "./payment-headers.js";
import paymentLinesRouter from "./payment-lines.js";
import journalEntriesRouter from "./journal-entries.js";
import invoicesRouter from "./invoices.js";
import taxInvoicesRouter from "./tax-invoices.js";
import statementsRouter from "./statements.js";
import menuAllocationRouter from "./menu-allocation.js";
import accountServiceProfilesRouter from "./account-service-profiles.js";
import costLinesRouter from "./cost-lines.js";
import allApplicationsRouter from "./all-applications.js";
import teamsRouter from "./teams.js";
import kpiRouter from "./kpi.js";
import applicationFormsRouter from "./application-forms.js";
import tenantSettingsRouter from "./tenant-settings.js";
import superAdminRouter from "./superadmin.js";
import platformPlansRouter from "./platformPlans.js";
import platformCrmRouter from "./platform-crm.js";
import adminDataImportRouter from "./admin-data-import.js";
import platformIntegrationsRouter from "./platform-integrations.js";
import portalRouter from "./portal.js";
import communityRouter from "./community.js";
import schoolingConsultationsRouter from "./schooling-consultations.js";
import studyAbroadConsultationsRouter from "./study-abroad-consultations.js";
import generalConsultationsRouter from "./general-consultations.js";
import publicConsultationsRouter from "./public-consultations.js";
import { tenantResolver } from "../middleware/tenantResolver.js";
import { runWithTenantSchema, tenantSchemaExists, pool } from "@workspace/db";
import type { Request, Response, NextFunction } from "express";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(publicConsultationsRouter);
// ── Tenant resolver: reads X-Organisation-Id header → req.tenantId / req.tenant ──
router.use(tenantResolver);
// ── Tenant Schema 미들웨어 ────────────────────────────────────────────────────
// tenantResolver 이후 실행. 테넌트의 PostgreSQL schema가 존재하면
// AsyncLocalStorage context에서 요청을 실행 → 모든 db 쿼리가 tenant schema 사용.
// schema 미존재 → public schema 사용 (기존 동작 유지)
router.use(async (req: Request, res: Response, next: NextFunction) => {
  const subdomain = (req as any).tenant?.subdomain as string | undefined;
  if (!subdomain) return next();
  try {
    const schemaExists = await tenantSchemaExists(subdomain, pool);
    if (schemaExists) {
      runWithTenantSchema(subdomain, next);
    } else {
      next();
    }
  } catch {
    next();
  }
});
// ── Public settings route (theme, no auth) — registered early before auth-guarded routers ──
router.use("/settings", tenantSettingsRouter);
router.use("/auth", authRouter);
router.use(portalRouter);
router.use(communityRouter);
router.use("/users", usersRouter);
router.use(packagesRouter);
router.use(applicationsRouter);
router.use(contractsRouter);
router.use(financeRouter);
router.use(dashboardRouter);
router.use(publicRouter);
router.use(servicesRouter);
router.use(myAccountingRouter);
router.use(reportsRouter);
router.use(notificationsRouter);
router.use(tasksRouter);
router.use(notesRouter);
router.use("/data-manager", dataManagerRouter);
router.use(ledgerRouter);
router.use(documentsRouter);
router.use("/settings", settingsRouter);
router.use(settingsLookupsRouter);
router.use(chatbotRouter);
router.use(aiRouter);
router.use(contractFinanceRouter);
router.use("/contract-signing", contractSigningRouter);
router.use(crmContactsRouter);
router.use(crmLeadsRouter);
router.use(crmQuotesRouter);
router.use(accountingCoaRouter);
router.use(accountingArApRouter);
router.use(accountingPaymentsRouter);
router.use(servicesStudyAbroadRouter);
router.use(servicesAccommodationRouter);
router.use(servicesPickupRouter);
router.use(servicesInternshipRouter);
router.use(servicesGuardianRouter);
router.use(servicesOtherRouter);
router.use(servicesVisaRouter);
router.use(servicesTourRouter);
router.use(campApplicationsRouter);
router.use(campServicesRouter);
router.use(dashboardCrmRouter);
router.use(dashboardV2Router);
router.use(crmAccountsRouter);
router.use(productCatalogRouter);
router.use(accountingTransactionsRouter);
router.use(quoteProductsRouter);
router.use(crmContractsRouter);
router.use(paymentHeadersRouter);
router.use(paymentLinesRouter);
router.use(journalEntriesRouter);
router.use("/invoices", invoicesRouter);
router.use(taxInvoicesRouter);
router.use(statementsRouter);
router.use(menuAllocationRouter);
router.use(accountServiceProfilesRouter);
router.use(costLinesRouter);
router.use(allApplicationsRouter);
router.use(teamsRouter);
router.use("/kpi", kpiRouter);
router.use(applicationFormsRouter);
router.use(superAdminRouter);
router.use(platformPlansRouter);
router.use(platformCrmRouter);
router.use(platformIntegrationsRouter);
router.use("/admin", adminDataImportRouter);
router.use(campPhotosRouter);
router.use(schoolingConsultationsRouter);
router.use(studyAbroadConsultationsRouter);
router.use(generalConsultationsRouter);

export default router;
