import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import storageRouter from "./storage.js";
import authRouter from "./auth.js";
import usersRouter from "./users.js";
import packagesRouter from "./packages.js";
import applicationsRouter from "./applications.js";
import contractsRouter from "./contracts.js";
import financeRouter from "./finance.js";
import dashboardRouter from "./dashboard.js";
import publicRouter from "./public.js";
import servicesRouter from "./services.js";
import myAccountingRouter from "./my-accounting.js";
import reportsRouter from "./reports.js";
import notificationsRouter from "./notifications.js";
import tasksRouter from "./tasks.js";
import notesRouter from "./notes.js";
import dataManagerRouter from "./data-manager.js";
import ledgerRouter from "./ledger.js";
import documentsRouter from "./documents.js";
import settingsRouter from "./settings.js";
import chatbotRouter from "./chatbot.js";
import aiRouter from "./ai.js";
import contractFinanceRouter from "./contract-finance.js";
import crmContactsRouter from "./crm-contacts.js";
import crmLeadsRouter from "./crm-leads.js";
import crmQuotesRouter from "./crm-quotes.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use(packagesRouter);
router.use(applicationsRouter);
router.use(contractsRouter);
router.use(financeRouter);
router.use(dashboardRouter);
router.use(publicRouter);
router.use(servicesRouter);
router.use(myAccountingRouter);
router.use(reportsRouter);
router.use(notificationsRouter);
router.use(tasksRouter);
router.use(notesRouter);
router.use("/data-manager", dataManagerRouter);
router.use(ledgerRouter);
router.use(documentsRouter);
router.use("/settings", settingsRouter);
router.use(chatbotRouter);
router.use(aiRouter);
router.use(contractFinanceRouter);
router.use(crmContactsRouter);
router.use(crmLeadsRouter);
router.use(crmQuotesRouter);

export default router;
