import {
  pgTable,
  uuid,
  varchar,
  text,
  timestamp,
  boolean,
  integer,
  decimal,
  date,
  jsonb,
  unique,
} from "drizzle-orm/pg-core";
import { accounts } from "./crm";

export const accountServiceCategories = pgTable("account_service_categories", {
  id:          uuid("id").primaryKey().defaultRandom(),
  accountId:   uuid("account_id").notNull().references(() => accounts.id, { onDelete: "cascade" }),
  serviceType: varchar("service_type", { length: 50 }).notNull(),
  isActive:    boolean("is_active").notNull().default(true),
  notes:       text("notes"),
  createdAt:   timestamp("created_at").notNull().defaultNow(),
  updatedAt:   timestamp("updated_at").notNull().defaultNow(),
}, (t) => [
  unique().on(t.accountId, t.serviceType),
]);

export const accountHomestayProfiles = pgTable("account_homestay_profiles", {
  id:                   uuid("id").primaryKey().defaultRandom(),
  accountId:            uuid("account_id").notNull().references(() => accounts.id, { onDelete: "cascade" }),
  roomType:             varchar("room_type",          { length: 100 }),
  accommodationType:    varchar("accommodation_type", { length: 100 }),
  mealIncluded:         varchar("meal_included",      { length: 50  }),
  weeklyRate:           decimal("weekly_rate",        { precision: 10, scale: 2 }),
  partnerWeeklyCost:    decimal("partner_weekly_cost",{ precision: 10, scale: 2 }),
  distanceToSchool:     varchar("distance_to_school", { length: 200 }),
  maxStudents:          integer("max_students").default(1),
  availableFrom:        date("available_from"),
  hostName:             varchar("host_name",          { length: 255 }),
  hostContact:          varchar("host_contact",       { length: 100 }),
  propertyAddress:      text("property_address"),
  amenities:            jsonb("amenities"),
  houseRules:           text("house_rules"),
  isCurrentlyOccupied:  boolean("is_currently_occupied").notNull().default(false),
  currentStudentCount:  integer("current_student_count").notNull().default(0),
  isActive:             boolean("is_active").notNull().default(true),
  notes:                text("notes"),
  createdAt:            timestamp("created_at").notNull().defaultNow(),
  updatedAt:            timestamp("updated_at").notNull().defaultNow(),
});

export const accountPickupProfiles = pgTable("account_pickup_profiles", {
  id:              uuid("id").primaryKey().defaultRandom(),
  accountId:       uuid("account_id").notNull().references(() => accounts.id, { onDelete: "cascade" }),
  driverName:      varchar("driver_name",      { length: 255 }),
  driverContact:   varchar("driver_contact",   { length: 100 }),
  driverLicenseNo: varchar("driver_license_no",{ length: 100 }),
  vehicleMake:     varchar("vehicle_make",     { length: 100 }),
  vehicleModel:    varchar("vehicle_model",    { length: 100 }),
  vehicleColor:    varchar("vehicle_color",    { length: 50  }),
  plateNumber:     varchar("plate_number",     { length: 50  }),
  vehicleYear:     integer("vehicle_year"),
  capacity:        integer("capacity"),
  serviceArea:     varchar("service_area",     { length: 255 }),
  serviceAirports: jsonb("service_airports"),
  baseRate:        decimal("base_rate",        { precision: 10, scale: 2 }),
  nightRate:       decimal("night_rate",       { precision: 10, scale: 2 }),
  extraStopRate:   decimal("extra_stop_rate",  { precision: 10, scale: 2 }),
  isAvailable:     boolean("is_available").notNull().default(true),
  isActive:        boolean("is_active").notNull().default(true),
  notes:           text("notes"),
  createdAt:       timestamp("created_at").notNull().defaultNow(),
  updatedAt:       timestamp("updated_at").notNull().defaultNow(),
});

export const accountCompanyProfiles = pgTable("account_company_profiles", {
  id:                  uuid("id").primaryKey().defaultRandom(),
  accountId:           uuid("account_id").notNull().references(() => accounts.id, { onDelete: "cascade" }),
  industry:            varchar("industry",       { length: 100 }),
  companySize:         varchar("company_size",   { length: 50  }),
  abn:                 varchar("abn",            { length: 50  }),
  contactPerson:       varchar("contact_person", { length: 255 }),
  contactTitle:        varchar("contact_title",  { length: 100 }),
  contactEmail:        varchar("contact_email",  { length: 255 }),
  contactPhone:        varchar("contact_phone",  { length: 100 }),
  availablePositions:  jsonb("available_positions"),
  placementFeeType:    varchar("placement_fee_type", { length: 50 }),
  placementFee:        decimal("placement_fee",  { precision: 10, scale: 2 }),
  requiresPoliceCheck: boolean("requires_police_check").notNull().default(false),
  requiresWwcc:        boolean("requires_wwcc").notNull().default(false),
  dressCode:           varchar("dress_code",     { length: 100 }),
  workAddress:         text("work_address"),
  isActive:            boolean("is_active").notNull().default(true),
  notes:               text("notes"),
  createdAt:           timestamp("created_at").notNull().defaultNow(),
  updatedAt:           timestamp("updated_at").notNull().defaultNow(),
}, (t) => [
  unique().on(t.accountId),
]);

export const accountSchoolProfiles = pgTable("account_school_profiles", {
  id:                    uuid("id").primaryKey().defaultRandom(),
  accountId:             uuid("account_id").notNull().references(() => accounts.id, { onDelete: "cascade" }),
  cricosCode:            varchar("cricos_code",          { length: 50 }),
  rtoCode:               varchar("rto_code",             { length: 50 }),
  institutionType:       jsonb("institution_type"),
  enrolmentOfficer:      varchar("enrolment_officer",    { length: 255 }),
  enrolmentEmail:        varchar("enrolment_email",      { length: 255 }),
  enrolmentPhone:        varchar("enrolment_phone",      { length: 100 }),
  intakeMonths:          jsonb("intake_months"),
  academicCalendar:      varchar("academic_calendar",    { length: 50 }),
  defaultCommissionRate: decimal("default_commission_rate", { precision: 8, scale: 4 }),
  commissionBasis:       varchar("commission_basis",     { length: 30 }),
  availableCourses:      jsonb("available_courses"),
  canSponsorStudentVisa: boolean("can_sponsor_student_visa").notNull().default(true),
  oshcRequired:          boolean("oshc_required").notNull().default(true),
  emergencyContact:      varchar("emergency_contact",    { length: 100 }),
  isActive:              boolean("is_active").notNull().default(true),
  notes:                 text("notes"),
  createdAt:             timestamp("created_at").notNull().defaultNow(),
  updatedAt:             timestamp("updated_at").notNull().defaultNow(),
}, (t) => [
  unique().on(t.accountId),
]);

export const accountTourProfiles = pgTable("account_tour_profiles", {
  id:                    uuid("id").primaryKey().defaultRandom(),
  accountId:             uuid("account_id").notNull().references(() => accounts.id, { onDelete: "cascade" }),
  tourName:              varchar("tour_name",              { length: 255 }).notNull(),
  tourType:              varchar("tour_type",              { length: 50  }),
  tourCategory:          varchar("tour_category",          { length: 100 }),
  durationHours:         integer("duration_hours"),
  durationDays:          integer("duration_days"),
  minParticipants:       integer("min_participants").default(1),
  maxParticipants:       integer("max_participants"),
  defaultPickupLocation: varchar("default_pickup_location",{ length: 255 }),
  pickupAvailable:       boolean("pickup_available").notNull().default(false),
  operatesOn:            jsonb("operates_on"),
  departureTime:         varchar("departure_time",         { length: 50 }),
  returnTime:            varchar("return_time",            { length: 50 }),
  inclusions:            text("inclusions"),
  exclusions:            text("exclusions"),
  adultRetailPrice:      decimal("adult_retail_price",     { precision: 10, scale: 2 }),
  childRetailPrice:      decimal("child_retail_price",     { precision: 10, scale: 2 }),
  partnerCost:           decimal("partner_cost",           { precision: 10, scale: 2 }),
  advanceBookingDays:    integer("advance_booking_days"),
  cancellationPolicy:    text("cancellation_policy"),
  bookingContact:        varchar("booking_contact",        { length: 255 }),
  guideLanguages:        jsonb("guide_languages"),
  thumbnailUrl:          varchar("thumbnail_url",          { length: 500 }),
  isActive:              boolean("is_active").notNull().default(true),
  notes:                 text("notes"),
  createdAt:             timestamp("created_at").notNull().defaultNow(),
  updatedAt:             timestamp("updated_at").notNull().defaultNow(),
});
