import {
  pgTable,
  uuid,
  varchar,
  text,
  decimal,
  timestamp,
  boolean,
  integer,
  jsonb,
  date,
  unique,
  index,
  AnyPgColumn,
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { users } from "./users";
import { contracts } from "./contracts";
import { products } from "./packages";
import { accounts, contacts } from "./crm";

export const exchangeRates = pgTable(
  "exchange_rates",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    fromCurrency: varchar("from_currency", { length: 10 }).notNull(),
    toCurrency: varchar("to_currency", { length: 10 }).notNull().default("AUD"),
    rate: decimal("rate", { precision: 12, scale: 6 }).notNull(),
    source: varchar("source", { length: 50 }).default("manual"),
    effectiveDate: date("effective_date").notNull(),
    createdBy: uuid("created_by").references(() => users.id),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (t) => [unique().on(t.fromCurrency, t.toCurrency, t.effectiveDate)]
);

export const banking = pgTable("banking", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id").references(() => users.id),
  bankName: varchar("bank_name", { length: 255 }),
  accountNumber: varchar("account_number", { length: 100 }),
  accountHolder: varchar("account_holder", { length: 255 }),
  bankCode: varchar("bank_code", { length: 50 }),
  countryCode: varchar("country_code", { length: 10 }),
  defaultCurrency: varchar("default_currency", { length: 10 }),
  isPrimary: boolean("is_primary").default(false),
  status: varchar("status", { length: 20 }).default("active"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// ── Contract Finance Items ─────────────────────────────────────────────────
export const contractFinanceItems = pgTable(
  "contract_finance_items",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    contractId: uuid("contract_id").references(() => contracts.id).notNull(),
    itemType: varchar("item_type", { length: 20 }).notNull(), // 'receivable' | 'payable'
    // Receivable: 'client_invoice' | 'agent_invoice'
    // Payable:    'cc_agent' | 'cc_institute' | 'cc_hotel' | 'cc_pickup' | 'cc_tour' | 'cc_settlement' | 'cc_misc'
    itemCategory: varchar("item_category", { length: 50 }).notNull(),
    // Revenue: 'RC-CAMP' | 'RC-DIRECT'
    // Cost:    'CC-AGENT' | 'CC-INSTITUTE' | 'CC-HOTEL' | 'CC-PICKUP' | 'CC-TOUR' | 'CC-SETTLEMENT' | 'CC-MISC'
    costCenter: varchar("cost_center", { length: 30 }),
    label: varchar("label", { length: 255 }).notNull(),
    linkedProductId: uuid("linked_product_id").references(() => products.id),
    linkedPartnerId: uuid("linked_partner_id").references(() => accounts.id, { onDelete: "set null" }),
    linkedAgentId: uuid("linked_agent_id").references(() => users.id),
    estimatedAmount: decimal("estimated_amount", { precision: 12, scale: 2 }).notNull(),
    actualAmount: decimal("actual_amount", { precision: 12, scale: 2 }),
    currency: varchar("currency", { length: 10 }).default("AUD"),
    commissionType: varchar("commission_type", { length: 20 }), // 'percentage' | 'fixed' | null
    commissionRate: decimal("commission_rate", { precision: 5, scale: 2 }),
    commissionFixed: decimal("commission_fixed", { precision: 12, scale: 2 }),
    dueDate: date("due_date"),
    paidDate: date("paid_date"),
    // 'pending' | 'invoiced' | 'partial' | 'paid' | 'overdue' | 'cancelled'
    status: varchar("status", { length: 20 }).default("pending"),
    isAutoGenerated: boolean("is_auto_generated").default(true),
    isDeleted: boolean("is_deleted").default(false),
    notes: text("notes"),
    createdAt: timestamp("created_at").defaultNow(),
    updatedAt: timestamp("updated_at").defaultNow(),
  },
  (t) => [
    index("idx_cfi_contract").on(t.contractId),
    index("idx_cfi_item_type").on(t.itemType, t.status),
  ]
);

// ── User Ledger ────────────────────────────────────────────────────────────
export const userLedger = pgTable(
  "user_ledger",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    contractId: uuid("contract_id").references(() => contracts.id).notNull(),
    financeItemId: uuid("finance_item_id").references(() => contractFinanceItems.id).notNull(),
    userId: uuid("user_id").references(() => users.id).notNull(),
    entryType: varchar("entry_type", { length: 10 }).notNull(), // 'credit' | 'debit'
    costCenter: varchar("cost_center", { length: 30 }),
    amount: decimal("amount", { precision: 12, scale: 2 }).notNull(),
    currency: varchar("currency", { length: 10 }).default("AUD"),
    description: varchar("description", { length: 500 }),
    // 'invoice' | 'receipt' | 'commission' | 'settlement' | 'manual'
    referenceType: varchar("reference_type", { length: 20 }),
    referenceId: uuid("reference_id"),
    transactionDate: date("transaction_date").notNull(),
    // 'pending' | 'confirmed' | 'reconciled'
    status: varchar("status", { length: 20 }).default("confirmed"),
    createdBy: uuid("created_by").references(() => users.id).notNull(),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (t) => [
    index("idx_ul_user").on(t.userId, t.transactionDate),
    index("idx_ul_contract").on(t.contractId),
    index("idx_ul_finance_item").on(t.financeItemId),
  ]
);

// ── Invoices (extended) ────────────────────────────────────────────────────
export const invoices = pgTable("invoices", {
  id: uuid("id").primaryKey().defaultRandom(),
  invoiceNumber: varchar("invoice_number", { length: 50 }).unique(),
  contractId: uuid("contract_id").references(() => contracts.id),
  invoiceType: varchar("invoice_type", { length: 20 }).notNull(),
  recipientId: uuid("recipient_id").references(() => users.id),
  lineItems: jsonb("line_items"),
  subtotal: decimal("subtotal", { precision: 12, scale: 2 }),
  taxAmount: decimal("tax_amount", { precision: 12, scale: 2 }),
  gstAmount: decimal("gst_amount", { precision: 12, scale: 2 }), // Tax invoice field
  totalAmount: decimal("total_amount", { precision: 12, scale: 2 }),
  originalCurrency: varchar("original_currency", { length: 10 }),
  originalAmount: decimal("original_amount", { precision: 12, scale: 2 }),
  audEquivalent: decimal("aud_equivalent", { precision: 12, scale: 2 }),
  exchangeRateToAud: decimal("exchange_rate_to_aud", { precision: 10, scale: 6 }),
  rateAppliedAt: timestamp("rate_applied_at"),
  currency: varchar("currency", { length: 10 }).default("AUD"),
  status: varchar("status", { length: 20 }).default("draft"),
  issuedAt: timestamp("issued_at"),
  dueDate: date("due_date"),
  paidAt: timestamp("paid_at"),
  notes: text("notes"),
  ledgerEntryId: uuid("ledger_entry_id"),
  // New fields
  financeItemId: uuid("finance_item_id").references(() => contractFinanceItems.id),
  agentId: uuid("agent_id").references(() => users.id),
  commissionAmount: decimal("commission_amount", { precision: 12, scale: 2 }),
  netAmount: decimal("net_amount", { precision: 12, scale: 2 }),
  createdBy: uuid("created_by").references(() => users.id),
  parentInvoiceId: uuid("parent_invoice_id").references((): AnyPgColumn => invoices.id),
  isRecurring: boolean("is_recurring").default(false).notNull(),
  recurringCycle: varchar("recurring_cycle", { length: 20 }),
  recurringSeq: integer("recurring_seq"),
  contractProductId: uuid("contract_product_id"),
  balanceDue: decimal("balance_due", { precision: 12, scale: 2 }),
  arStatus: varchar("ar_status", { length: 20 }).default("invoiced"),
  // Tax Invoice fields (optional - nullable for non-tax invoices)
  invoiceRef: varchar("invoice_ref", { length: 50 }),
  schoolAccountId: uuid("school_account_id"),
  studentAccountId: uuid("student_account_id"),
  programName: varchar("program_name", { length: 255 }),
  studentName: varchar("student_name", { length: 255 }),
  courseStartDate: date("course_start_date"),
  courseEndDate: date("course_end_date"),
  isGstFree: boolean("is_gst_free").default(false),
  pdfUrl: varchar("pdf_url", { length: 500 }),
  sentToEmail: varchar("sent_to_email", { length: 255 }),
  sentAt: timestamp("sent_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const transactions = pgTable("transactions", {
  id: uuid("id").primaryKey().defaultRandom(),
  contractId: uuid("contract_id").references(() => contracts.id),
  invoiceId: uuid("invoice_id").references(() => invoices.id),
  bankAccountId: uuid("bank_account_id").references(() => banking.id),
  transactionType: varchar("transaction_type", { length: 20 }).notNull(),
  amount: decimal("amount", { precision: 12, scale: 2 }),
  originalCurrency: varchar("original_currency", { length: 10 }),
  originalAmount: decimal("original_amount", { precision: 12, scale: 2 }),
  audEquivalent: decimal("aud_equivalent", { precision: 12, scale: 2 }),
  exchangeRateToAud: decimal("exchange_rate_to_aud", { precision: 10, scale: 6 }),
  currency: varchar("currency", { length: 10 }).default("AUD"),
  description: varchar("description", { length: 500 }),
  bankReference: varchar("bank_reference", { length: 200 }),
  transactionDate: date("transaction_date"),
  ledgerEntryId: uuid("ledger_entry_id"),
  createdBy: uuid("created_by").references(() => users.id),
  createdAt: timestamp("created_at").defaultNow(),
  // Extended fields for Create Transaction form
  accountId:       uuid("account_id").references(() => accounts.id, { onDelete: "set null" }),
  contactId:       uuid("contact_id").references(() => contacts.id, { onDelete: "set null" }),
  paymentInfoId:   uuid("payment_info_id"),
  costCenterCode:  varchar("cost_center_code", { length: 10 }),
  creditAmount:    decimal("credit_amount", { precision: 12, scale: 2 }),
  status:          varchar("status", { length: 20 }).default("Active"),
});

// ── Receipts (extended) ────────────────────────────────────────────────────
export const receipts = pgTable("receipts", {
  id: uuid("id").primaryKey().defaultRandom(),
  receiptNumber: varchar("receipt_number", { length: 50 }).unique(),
  invoiceId: uuid("invoice_id").references(() => invoices.id),
  payerId: uuid("payer_id").references(() => users.id),
  amount: decimal("amount", { precision: 12, scale: 2 }),
  originalCurrency: varchar("original_currency", { length: 10 }),
  originalAmount: decimal("original_amount", { precision: 12, scale: 2 }),
  audEquivalent: decimal("aud_equivalent", { precision: 12, scale: 2 }),
  exchangeRateToAud: decimal("exchange_rate_to_aud", { precision: 10, scale: 6 }),
  currency: varchar("currency", { length: 10 }).default("AUD"),
  paymentMethod: varchar("payment_method", { length: 50 }),
  receiptDate: date("receipt_date"),
  status: varchar("status", { length: 20 }).default("confirmed"),
  notes: text("notes"),
  ledgerEntryId: uuid("ledger_entry_id"),
  // New fields
  financeItemId: uuid("finance_item_id").references(() => contractFinanceItems.id),
  confirmedBy: uuid("confirmed_by").references(() => users.id),
  confirmedAt: timestamp("confirmed_at"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const accountLedgerEntries = pgTable(
  "account_ledger_entries",
  {
    id:               uuid("id").primaryKey().defaultRandom(),
    accountId:        uuid("account_id").references(() => accounts.id, { onDelete: "cascade" }).notNull(),
    sourceType:       varchar("source_type", { length: 50 }).notNull(),
    sourceId:         uuid("source_id").notNull(),
    contractId:       uuid("contract_id").references(() => contracts.id),
    entryType:        varchar("entry_type", { length: 10 }).notNull(),
    amount:           decimal("amount", { precision: 12, scale: 2 }).notNull(),
    currency:         varchar("currency", { length: 10 }).default("AUD"),
    originalAmount:   decimal("original_amount", { precision: 12, scale: 2 }),
    originalCurrency: varchar("original_currency", { length: 10 }),
    audEquivalent:    decimal("aud_equivalent", { precision: 12, scale: 2 }),
    exchangeRateToAud: decimal("exchange_rate_to_aud", { precision: 10, scale: 6 }),
    status:           varchar("status", { length: 20 }).default("pending"),
    description:      varchar("description", { length: 500 }),
    entryDate:        date("entry_date").notNull(),
    createdBy:        uuid("created_by").references(() => users.id),
    createdAt:        timestamp("created_at").defaultNow(),
    updatedAt:        timestamp("updated_at").defaultNow(),
  },
  (t) => [
    index("idx_ledger_account").on(t.accountId, t.entryDate),
    index("idx_ledger_source").on(t.sourceType, t.sourceId),
    index("idx_ledger_contract").on(t.contractId),
  ]
);

export const insertInvoiceSchema = createInsertSchema(invoices).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});
export const insertTransactionSchema = createInsertSchema(transactions).omit({
  id: true,
  createdAt: true,
});
export const insertExchangeRateSchema = createInsertSchema(exchangeRates).omit({
  id: true,
  createdAt: true,
});
export const insertLedgerEntrySchema = createInsertSchema(accountLedgerEntries).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});
export const insertContractFinanceItemSchema = createInsertSchema(contractFinanceItems).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});
export const insertUserLedgerSchema = createInsertSchema(userLedger).omit({
  id: true,
  createdAt: true,
});

export type InsertInvoice = z.infer<typeof insertInvoiceSchema>;
export type Invoice = typeof invoices.$inferSelect;
export type InsertTransaction = z.infer<typeof insertTransactionSchema>;
export type Transaction = typeof transactions.$inferSelect;
export type ExchangeRate = typeof exchangeRates.$inferSelect;
export type AccountLedgerEntry = typeof accountLedgerEntries.$inferSelect;
export type InsertLedgerEntry = z.infer<typeof insertLedgerEntrySchema>;
export type ContractFinanceItem = typeof contractFinanceItems.$inferSelect;
export type InsertContractFinanceItem = z.infer<typeof insertContractFinanceItemSchema>;
export type UserLedger = typeof userLedger.$inferSelect;
export type InsertUserLedger = z.infer<typeof insertUserLedgerSchema>;
